### PR TITLE
Update bazel version to 7.0.1

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/198)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/198)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh and @stevenwarejones)

___
*[`.bazelversion` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/198#-NpgFI1wBoikBlpgLgoC:-NpgFI1wBoikBlpgLgoD:b-ftv21p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/427cbf5045964b971d6dd65b8ac1b1c24436b26c/.bazelversion#L1)):*
> ```
> 7.0.1
> ```

nit: 7.0.2 just got released if you're updating anyway

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/198)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/198)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

___
*[`.bazelversion` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/198#-NpgFI1wBoikBlpgLgoC:-NpuOGfG2z9OyyJqE9aF:b-smrvll) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/427cbf5045964b971d6dd65b8ac1b1c24436b26c/.bazelversion#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: 7.0.2 just got released if you're updating anyway
</blockquote></details>

I will keep it as 7.0.1 to be consistent with other repos.

**Pull request merged**
