### PR TITLE
Drop unimplemented/unused exchange methods.

### PR DESCRIPTION
**Pull request by SanjayVas**
These have been unimplemented for so long that having them in the API definition is misleading and results in maintanence overhead.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/143)

**Review by stevenwarejones — APPROVED** [review]
I guess if we ever need them, we could just reintroduce them? I could see us needing these in the future, possibly. 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/143#-:-NXAsVod8Yxi3jNp-ebP:b-1v2xh4)* status: 0 of 5 files reviewed, all discussions resolved

**Review by SanjayVas — COMMENTED** [review]
Yeah, just reintroduce them as-needed.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/143#-:-NXB5Oyg0yAGRLOpXIKO:blcudza)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/143)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
