### PR TITLE
Remove ShareShuffleSketchParams

### PR DESCRIPTION
**Pull request by renjiezh**
In HMSS protocol we use FrequencyVector as the counterpart of Sketch in LLv2. This PR is to correct the naming. Besides, the content of FrequencyVectorParams (which was SketchParams) is only the ring modulus. Thus remove it.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @ple13)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @renjiezh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210#-O1rSv4KDhScy2irZT_U:-O1rSv4KDhScy2irZT_V:b4nit8h) (no related file):*
I assume this is due to the fact that HMSS doesn't actually use a sketch? If so, please add that to the PR description.

___

**Review by SanjayVas — COMMENTED** [review]
This would normally be a breaking change, but nobody is using HMSS yet. That is to say it would break EDPs that fulfill HMSS requisitions, which right now is only our test environment simulators.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210#-:-O1rgJ9cCBEr-Osd1rsv:begj6ia)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

**Review by renjiezh — COMMENTED** [review]
Thank you sanjay to illustrate it. 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210#-:-O1sBh8v1Q-V17Cn6cPX:b-1dpekz)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210#-O1rSv4KDhScy2irZT_U:-O1sC520BeN9PPuaeQ8s:b-ggzrcl) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume this is due to the fact that HMSS doesn't actually use a sketch? If so, please add that to the PR description.
</blockquote></details>

PR description added.

___

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210#-O1sGeab8_bNkYPf7f5C:-O1sGeab8_bNkYPf7f5D:bfn6sf5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e72bcd049d592c58e51276abeaa4565611b6597d/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L215)):*
> ```proto
>     //
>     // For ReachAndFrequency Measurement, it is required to be greater than
>     // (1 + `maximum_frequency`).
> ```

It's worth noting that the maximum frequency is the number of EDPs multiplied by the maximum reportable frequency.

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210#-O1sGeab8_bNkYPf7f5C:-O1wFJt59yHxVqUpTcH7:b-97vxst) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e72bcd049d592c58e51276abeaa4565611b6597d/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L215)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It's worth noting that the maximum frequency is the number of EDPs multiplied by the maximum reportable frequency.
</blockquote></details>

+1. It's more precise to be written as `1 + maximum_combined_frequency` or `1 + maximum_frequency*#EDPs`.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/210)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Pull request merged**
