### PR TITLE
Add measurement state to requisition and list requisitions filter.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
For solving this issue: https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/466

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/94)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/94)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition.proto, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/94#-MyyLAmR2TEHMT8lqibq:-MyyLAmR2TEHMT8lqibr:b1oh1kg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c21c87496b3f2ed0801dfb1e1027d02dd542a80b/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L180)):*
> ```protobuf
>   Refusal refusal = 12;
> 
>   // Denormalized `state` field from `measurement`. Immutable. Output-only.
> ```

Definitely not immutable. The state can change throughout the lifetime of a Requisition.



_Code quote:_
```protobuf
 Immutable.
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/94)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition.proto, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/94#-MyyLAmR2TEHMT8lqibq:-Myyr7g93Nr1rN253AR7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c21c87496b3f2ed0801dfb1e1027d02dd542a80b/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L180)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Definitely not immutable. The state can change throughout the lifetime of a Requisition.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
