### PR TITLE
Update EventFilter definition with CEL proto

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)

### CODE REVIEW

**Review by duliomatos1 — APPROVED** [review]
LGTM

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-:-MvczUJj3EFKnXfWOTO2:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: all files reviewed, 2 unresolved discussions (waiting on @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-Mve1RH1E-2QXD_0jBiP:-Mve1RH2-hjVmVL7OPSJ:b-poo60f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/85822919e454b9dc56adc71b22f27cdd5ace1260/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L34)):*
> ```protobuf
>     // Parsed CEL expression that contains non-PB and PB fields.
>     // PB fields : date, age, gender, vid.
>     // Non-PB fields : watch_duration, ...
> ```

I thought all the fields here would come from the relevant event template protobuf message.



_Code quote:_
```protobuf
// Non-PB fields : watch_duration, ...
```
___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-Mve1Mcz4odURWtLH37r:-Mve1Mcz4odURWtLH37s:bu5rkmb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/85822919e454b9dc56adc71b22f27cdd5ace1260/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L35)):*
> ```protobuf
>     // PB fields : date, age, gender, vid.
>     // Non-PB fields : watch_duration, ...
>     google.api.expr.v1alpha1.Expr filter_expression = 1;
> ```

We shouldn't import other API protos into our public API. Just use the string expression.



_Code quote:_
```protobuf
google.api.expr.v1alpha1.Expr filter_expression = 1;
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: all files reviewed, 2 unresolved discussions (waiting on @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-Mve1Mcz4odURWtLH37r:-Mve1rlQ6Io71OhQw3CQ:bpxr5gg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/85822919e454b9dc56adc71b22f27cdd5ace1260/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We shouldn't import other API protos into our public API. Just use the string expression.
</blockquote></details>

See https://google.aip.dev/213

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-Mve1RH1E-2QXD_0jBiP:-MveGyBP3q3kzKBsDNwS:b8x8pkd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/85822919e454b9dc56adc71b22f27cdd5ace1260/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought all the fields here would come from the relevant event template protobuf message.
</blockquote></details>

they should be coming from there. Would you like me to add this as a comment or do you think these comments are irrelevant and I should take these out. Keep in mind that all non-pb or pb fields has to be in the relevant event templates. Maybe I should write that?
___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-Mve1Mcz4odURWtLH37r:-MveHF-k9Lon6prxbhcy:byvi06s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/85822919e454b9dc56adc71b22f27cdd5ace1260/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See https://google.aip.dev/213
</blockquote></details>

great, thank you!

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-Mve1RH1E-2QXD_0jBiP:-MveKlzT9iKQ0mhtWLKQ:b-1iq18o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/85822919e454b9dc56adc71b22f27cdd5ace1260/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L34)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

they should be coming from there. Would you like me to add this as a comment or do you think these comments are irrelevant and I should take these out. Keep in mind that all non-pb or pb fields has to be in the relevant event templates. Maybe I should write that?
</blockquote></details>

Sorry, I misunderstood "PB" to be "protobuf" here rather than "Privacy Budget".

Regardless, I don't know if this is relevant here. Just maybe document that the expression is applied to the event template.
___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-MveLnR_EaNTMZnXCTUW:-MveLnR_EaNTMZnXCTUX:b3hdcum) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b7dedbc3eb666366b1836389801c02b754a9e960/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L30)):*
> ```protobuf
> message RequisitionSpec {
>   // Filter to apply to events.
>   message EventFilter {
> ```

How do we handle the fact that an EventGroup may have multiple template messages? I assume the filter expression should be able to reference any field in any of the templates.

Maybe we should have a name field in`EventTemplate`, and generate a wrapper message with one field per template so we can reference them by a short name?

@robinsons
___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-MveLjU01xqekVwxKGLE:-MveLjU01xqekVwxKGLF:bwm8015) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b7dedbc3eb666366b1836389801c02b754a9e960/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L34)):*
> ```protobuf
>     // PB fields : date, age, gender, vid.
>     // Non-PB fields : watch_duration, ...
>     string unparsed_filter_expression = 1;
> ```

nit: can probably just call this `expression`



_Code quote:_
```protobuf
unparsed_filter_expression
```

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-MveLnR_EaNTMZnXCTUW:-MvyO46vBWhRSRpAPNCM:b-434kkm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b7dedbc3eb666366b1836389801c02b754a9e960/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How do we handle the fact that an EventGroup may have multiple template messages? I assume the filter expression should be able to reference any field in any of the templates.

Maybe we should have a name field in`EventTemplate`, and generate a wrapper message with one field per template so we can reference them by a short name?

@robinsons
</blockquote></details>

That sounds like a reasonable approach. I would argue that generating a message can be lower priority, and until we support that we just have a step in the template creation process where the creator adds their template to some per-deployment "union template".

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @robinsons, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-MveLnR_EaNTMZnXCTUW:-Mvyalyx1MzZNh_ArsFR:byfltfe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b7dedbc3eb666366b1836389801c02b754a9e960/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L30)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

That sounds like a reasonable approach. I would argue that generating a message can be lower priority, and until we support that we just have a step in the template creation process where the creator adds their template to some per-deployment "union template".
</blockquote></details>

I worry about changing this after-the-fact, as all filter expressions would have to be updated if we change between field-per-template and union template.

For a union template, we'd have to figure out field renumbering. Furthermore, unless we're going to require that templates have disjoint sets of fields, then we'd also have to worry about conflicts. Hence why I recommended the field-per-template approach.

Ideally whatever message would only have the relevant templates for a given EventGroup rather than being an uber-message of all templates. Maybe we could have each template define an extension to some top-level Event message?

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-MveLnR_EaNTMZnXCTUW:-Mvz20ckDrqXyICKF8s_:b1jcns3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b7dedbc3eb666366b1836389801c02b754a9e960/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I worry about changing this after-the-fact, as all filter expressions would have to be updated if we change between field-per-template and union template.

For a union template, we'd have to figure out field renumbering. Furthermore, unless we're going to require that templates have disjoint sets of fields, then we'd also have to worry about conflicts. Hence why I recommended the field-per-template approach.

Ideally whatever message would only have the relevant templates for a given EventGroup rather than being an uber-message of all templates. Maybe we could have each template define an extension to some top-level Event message?
</blockquote></details>

Naming is hard. What I dubbed a "union template" is exactly what you are describing: a message with one field per template. I am agreeing with you, I just chose a misleading term :)

The only thing I was pushing back on was writing code to produce that generated message which has one field per template. If there's bandwidth for that, great, but otherwise it's simple to do it manually. Presumably EDPs will already be populating some sort of Event message so that they can apply filtering, and if their Event message doesn't have a field for a particular template, then they would just add it.

Also, what are your thoughts on having a shared top-level Event message with extensions vs. each EDP creating such an Event message internally? I don't know if we need the shared Event message, since EDPs will be applying filtering on their own, and the Kingdom and MP don't really care about the Event message (MP only cares about the templates which are already declared in the EventGroup).

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @robinsons, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-MveLnR_EaNTMZnXCTUW:-MvzbtbG3NV_c-WazwGW:bjd3f1q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b7dedbc3eb666366b1836389801c02b754a9e960/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L30)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Naming is hard. What I dubbed a "union template" is exactly what you are describing: a message with one field per template. I am agreeing with you, I just chose a misleading term :)

The only thing I was pushing back on was writing code to produce that generated message which has one field per template. If there's bandwidth for that, great, but otherwise it's simple to do it manually. Presumably EDPs will already be populating some sort of Event message so that they can apply filtering, and if their Event message doesn't have a field for a particular template, then they would just add it.

Also, what are your thoughts on having a shared top-level Event message with extensions vs. each EDP creating such an Event message internally? I don't know if we need the shared Event message, since EDPs will be applying filtering on their own, and the Kingdom and MP don't really care about the Event message (MP only cares about the templates which are already declared in the EventGroup).
</blockquote></details>

I figured using extensions on a shared Event message gives us the best tradeoffs, as it avoid the need to have to do any code generation. Each template can just be defined as an extension on Event, and anyone that needs to deal with Event messages for a given EventGroup just needs to load the correct templates into their extension registry.

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-MveLnR_EaNTMZnXCTUW:-Mvzw7kW8wexXvNqYJp7:bk89rsh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b7dedbc3eb666366b1836389801c02b754a9e960/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I figured using extensions on a shared Event message gives us the best tradeoffs, as it avoid the need to have to do any code generation. Each template can just be defined as an extension on Event, and anyone that needs to deal with Event messages for a given EventGroup just needs to load the correct templates into their extension registry.
</blockquote></details>

Is CEL able to evaluate message extensions?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @robinsons, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-MveLnR_EaNTMZnXCTUW:-Mw-0h7h0_YSNwrY3P0D:b-45re7h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b7dedbc3eb666366b1836389801c02b754a9e960/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L30)):*
Good question. I guess not. From an internal CEL expert:
> CEL does not support proto with extensions because they are a proto2 specific feature and thus can't be represented uniformly across proto2 and proto3 message types.

I guess that eliminates that option.

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @robinsons, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-Mve1RH1E-2QXD_0jBiP:-Mw7pE767jmsnYRKpryU:b75uoti) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/85822919e454b9dc56adc71b22f27cdd5ace1260/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, I misunderstood "PB" to be "protobuf" here rather than "Privacy Budget".

Regardless, I don't know if this is relevant here. Just maybe document that the expression is applied to the event template.
</blockquote></details>

thank you. I changed it so that it explains the fields reference an event template. I guess that's what you meant right? or maybe I am using these terms incorrectly. The expression is applied to the events themselves. wdyt?

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @robinsons, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-Mve1RH1E-2QXD_0jBiP:-Mw8Dued4UK8oDGReRQb:b-qcl86i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/85822919e454b9dc56adc71b22f27cdd5ace1260/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L34)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thank you. I changed it so that it explains the fields reference an event template. I guess that's what you meant right? or maybe I am using these terms incorrectly. The expression is applied to the events themselves. wdyt?
</blockquote></details>

Updated based on our last talk.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons)

___
*[src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89#-MveLnR_EaNTMZnXCTUW:-Mw8Zs8195I4leCJp0oi:b-n8izh6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b7dedbc3eb666366b1836389801c02b754a9e960/src/main/proto/wfa/measurement/api/v2alpha/requisition_spec.proto#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Good question. I guess not. From an internal CEL expert:
> CEL does not support proto with extensions because they are a proto2 specific feature and thus can't be represented uniformly across proto2 and proto3 message types.

I guess that eliminates that option.
</blockquote></details>

Closing this based on our discussion. Added comment on the requisition spec proto

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

**Pull request merged**
