### PR TITLE
Add explicit tasks for copying blobs to/from shared storage.

### PR DESCRIPTION
**Pull request by efoxepstein**
This changes ExchangeWorkflow to be much more explicit about sharing
data.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/51)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
i assume this is just part 1/2... we'll need the other outputs done this way as well.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/51#-:-MkPT8LR9SC-l4Xj39dq:bkbgb92)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jonmolle)

**Review by efoxepstein — COMMENTED** [review]
I basically just forgot to finish updating the textproto. I'll do that before merging this.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/51#-:-MkPoGZV0qIvko68Yjpv:b-xp5cpt)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jonmolle)

**Review by jonmolle — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/51)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @jonmolle)

**Review by jonmolle — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/51)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
