### PR TITLE
Add ModelProvider as parent of Certificate

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54)

### CODE REVIEW

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/model_provider.proto, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54#-MkiB4O27-Au4hDiFp-8:-MkiB4O31wSInPCDD5Nw:ba4erbl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0042a298583154f0b1bf76f780447999dd7f2f0d/src/main/proto/wfa/measurement/api/v2alpha/model_provider.proto#L49)):*
> ```protobuf
>   // Serialized `EncryptionPublicKey` for this `ModelProvider`, which can be
>   // verified using `certificate`. Required.
>   SignedData public_key = 4;
> ```

Do you want a `display_name` here too?

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @jonmolle, @stevenwarejones, and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/model_provider.proto, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54#-MkiB4O27-Au4hDiFp-8:-MkiCGmp-bmE8ip_ijmX:blsffk2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0042a298583154f0b1bf76f780447999dd7f2f0d/src/main/proto/wfa/measurement/api/v2alpha/model_provider.proto#L49)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Do you want a `display_name` here too?
</blockquote></details>

Sure, good idea, done

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle and @stevenwarejones)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle and @stevenwarejones)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle, @stevenwarejones, and @wangyaopw)

**Pull request merged**
