### PR TITLE
Combine data and seed for HMSS requisition fulfillment.

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/random_seed.proto` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-NpzfFO46QmtPcS_eBvE:-NpzfFO5A5JLXFHjTDSp:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d818fddeca262d9c866425b33eae584935cc0e06/src/main/proto/wfa/measurement/api/v2alpha/random_seed.proto#L24)):*
> ```proto
> 
> // A random seed that can be expanded into a deterministic blob using the
> // certain PRNG function.
> ```

nit



_Suggestion:_
```proto
// A random seed that can be expanded into a deterministic blob using a
// specific PRNG function.
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto` line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-NpzfeXZ5R9GDMxVwTIi:-NpzfeXZ5R9GDMxVwTIj:bepcyre) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d818fddeca262d9c866425b33eae584935cc0e06/src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto#L76)):*
> ```proto
>       //
>       //
>       // Signed by DataProvider and encrypted using the peer worker's
> ```

Reference the API field. I believe in this case this should be the `public_key` inside `DuchyEntry.honest_majority_share_shuffle` from the Requisition.



_Code quote:_
```proto
 peer worker's
```

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @renjiezh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq-efbn9Zlr5EQdVHcm:-Nq-efbn9Zlr5EQdVHcn:b5oev1e) (no related file):*
Also need a clear description of how the EDP should implement their part of the protocol somewhere. See the comment for ProtocolConfig.Protocol.direct.

___

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq-efbn9Zlr5EQdVHcm:-Nq05kTu1asK6byHzSCS:bply8tt) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also need a clear description of how the EDP should implement their part of the protocol somewhere. See the comment for ProtocolConfig.Protocol.direct.
</blockquote></details>

Done.
Added at ProtocolConfig.Protocol.HMSS

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 174 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq0B9FJAihpU8cDzwyL:-Nq0B9FJAihpU8cDzwyM:b-wdsxnf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c574f0fcfaa3ffaee2ad81e7a6a3f5c34cd6d44e/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L174)):*
> ```proto
>   //
>   // If present, must fulfill the requisition at the target Duchy.
>   string fulfilling_duchy = 16 [
> ```

I thought we were just going to use two DuchyEntries here, where one entry has the seed and the other entry doesn't? In that case, the Duchy to fulfill at is the one without the seed. No separate field needed.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 174 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq0B9FJAihpU8cDzwyL:-Nq0Bdo425pNvaVH8Y1S:b28c2fe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c574f0fcfaa3ffaee2ad81e7a6a3f5c34cd6d44e/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L174)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought we were just going to use two DuchyEntries here, where one entry has the seed and the other entry doesn't? In that case, the Duchy to fulfill at is the one without the seed. No separate field needed.
</blockquote></details>

I meant key, not seed.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 174 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq0B9FJAihpU8cDzwyL:-Nq0BbLICItsG0KC2qFN:b-rnazi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c574f0fcfaa3ffaee2ad81e7a6a3f5c34cd6d44e/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L174)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I meant key, not seed.
</blockquote></details>

Sure. I was thinking to make it explicit. Will update it.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 174 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq0B9FJAihpU8cDzwyL:-Nq0G0co9aO_7obGH6x3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c574f0fcfaa3ffaee2ad81e7a6a3f5c34cd6d44e/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L174)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Sure. I was thinking to make it explicit. Will update it.
</blockquote></details>

Done.

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 137 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq3ZT64Bs1fYPVU10LA:-Nq3ZT64Bs1fYPVU10LB:b-4fqcfe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5a060039888810251f978ab88628fa88c303b3b5/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L137)):*
> ```proto
>     message HonestMajorityShareShuffle {
>       // The `EncryptionPublicKey` generated by the `Duchy`.
>       SignedMessage public_key = 1 [(google.api.field_behavior) = REQUIRED];
> ```

This cannot be REQUIRED if one of the two entries won't have this set.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition.proto` line 137 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq3ZT64Bs1fYPVU10LA:-Nq3ibbc-DuPJh17573q:bxq2hv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/5a060039888810251f978ab88628fa88c303b3b5/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L137)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This cannot be REQUIRED if one of the two entries won't have this set.
</blockquote></details>

Done.
Thanks for catching it.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto` line 78 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq4O5nm4Zk76cfOEDwC:-Nq4O5nm4Zk76cfOEDwD:b-u0ydx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4f1d62dacd621936bc89d5baabeaf6ebd9705919/src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto#L78)):*
> ```proto
>       // worker's public key in
>       // Requisition.DuchyEntry.HonestMajorityShareShuffle.
>       EncryptedMessage secret_seed = 1;
> ```

This should be a SignedEncryptedMessage

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto` line 78 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq4O5nm4Zk76cfOEDwC:-Nq4S6umEqr2XxtmdFbH:bc7iu8d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4f1d62dacd621936bc89d5baabeaf6ebd9705919/src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto#L78)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This should be a SignedEncryptedMessage
</blockquote></details>

In public api we don't have SignedEncryptedMessage. So we will wrap the SignedMessage in a EncryptedMessage. As the comment said, it is an encrypted SignedMessage.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto` line 78 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq4O5nm4Zk76cfOEDwC:-Nq4YcIZAArOAK4gnGMU:b-17ptk6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4f1d62dacd621936bc89d5baabeaf6ebd9705919/src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto#L78)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

In public api we don't have SignedEncryptedMessage. So we will wrap the SignedMessage in a EncryptedMessage. As the comment said, it is an encrypted SignedMessage.
</blockquote></details>

Wrapping SignedMessage in EncryptedMessage is correct for our sign-then-encrypt pattern.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto` line 78 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/196#-Nq4O5nm4Zk76cfOEDwC:-Nq9xTIm-Kaj86fIQU-_:b-76z3ck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4f1d62dacd621936bc89d5baabeaf6ebd9705919/src/main/proto/wfa/measurement/api/v2alpha/requisition_fulfillment_service.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wrapping SignedMessage in EncryptedMessage is correct for our sign-then-encrypt pattern.
</blockquote></details>

Thanks for the comment update.

**Pull request merged**
