### PR TITLE
Add exchange workflow into exchange step

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/32)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/32)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/32#-MbIA_7z0ZJIDjM382WB:-MbIA_8-2rtrhyo5HkZC:b-k7fotk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/56446f42617c80e63496f28622b4e5506e3db69d/src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto#L48)):*
> ```protobuf
>   }
>   // Output-only.
>   SignedData data = 3;
> ```

Please use the existing `SignedData`.

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/32)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/32)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/32#-MbIA_7z0ZJIDjM382WB:-MbIWVdy3bvdLhuKKcQB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/56446f42617c80e63496f28622b4e5506e3db69d/src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use the existing `SignedData`.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
