### PR TITLE
Refactor ExchangeStep and ExchangeStepsService.

### PR DESCRIPTION
**Pull request by efoxepstein**
1. Updates ExchangeStep states to be more expressive.

2. Removes ListExchangeSteps and adds ListReadyExchangeSteps. This is a
more focused method to handle our only use case for Listing. We can
always add a generic List later, but this will be easier to implement
and makes the intent very clear.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZU0xZz3lFKP3GGCkMY:-MZU0xZz3lFKP3GGCkMZ:b591fsh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/90407740b8ddb8cbe2486bc4b4b65145b6d3d91d/src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto#L64)):*
> ```
> are in a FAILED state.
> ```
grammatical nit:
```
are in state `FAILED`.
```

This is referring to a specific state, not a set of states.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZU32nlBnOwfNZAtyFu:-MZU32nlBnOwfNZAtyFv:bv48edf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/90407740b8ddb8cbe2486bc4b4b65145b6d3d91d/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L34)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   // This is different from a standard List RPC endpoint because (a) it only
>   // includes results in state READY and (b) there are no filters or parent
>   // selection. Instead, the "parent" is either the DataProvider or the
>   // ModelProvider -- the party to execute the step.
> ```
</details>

For the public API, we should prefer the standard method for something like List when possible. In this case, it could be  implemented with filters and just not supporting certain filter values.

e.g. `PERMISSION_DENIED` error if the filter predicate would result in resources the caller doesn't have access to (wrong or no party), and `UNIMPLEMENTED` for any state other than `READY`.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZU2PiME9Iwf9qQTCpk:-MZU2PiME9Iwf9qQTCpl:b-f8ekun) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/90407740b8ddb8cbe2486bc4b4b65145b6d3d91d/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L66)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>   // Required. Only includes steps belonging to this party.
>   oneof party {
>     DataProvider.Key data_provider = 3;
>     ModelProvider.Key model_provider = 4;
>   }
> ```
</details>

Not strictly part of this PR but may affect it: I noticed that `RecurringExchange` is a top-level resource (i.e. does not have on of these parties as a parent). Does neither of these parties create the `RecurringExchange`?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZU32nlBnOwfNZAtyFu:-MZUNSGc8Fc94IMx8mqA:b-2j0ywx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/90407740b8ddb8cbe2486bc4b4b65145b6d3d91d/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   // This is different from a standard List RPC endpoint because (a) it only
>   // includes results in state READY and (b) there are no filters or parent
>   // selection. Instead, the "parent" is either the DataProvider or the
>   // ModelProvider -- the party to execute the step.
> ```
For the public API, we should prefer the standard method for something like List when possible. In this case, it could be  implemented with filters and just not supporting certain filter values.

e.g. `PERMISSION_DENIED` error if the filter predicate would result in resources the caller doesn't have access to (wrong or no party), and `UNIMPLEMENTED` for any state other than `READY`.
</blockquote></details>

Discussed offline. Changed to a custom method that returns a single item.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZU2PiME9Iwf9qQTCpk:-MZUKkte0ot07Wq4J7EI:b-d02doe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/90407740b8ddb8cbe2486bc4b4b65145b6d3d91d/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   // Required. Only includes steps belonging to this party.
>   oneof party {
>     DataProvider.Key data_provider = 3;
>     ModelProvider.Key model_provider = 4;
>   }
> ```
Not strictly part of this PR but may affect it: I noticed that `RecurringExchange` is a top-level resource (i.e. does not have on of these parties as a parent). Does neither of these parties create the `RecurringExchange`?
</blockquote></details>

Let's discuss this another time when we figure out how RecurringExchanges will be created.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZUoOZ_3d7OxdGh8yk-:-MZUoOZa9H8-JzZM5LR7:bxy5uge) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c54e8c1ab98862543aa7d9f742c0ae97e746c5f7/src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto#L53)):*
> ```
> TEMPORARILY
> ```
This name seems a little weird because it's still a terminal (i.e. non-temporary) state for this attempt. Non-blocking since I can't immediately come up with a better name to describe that the "temporary" part applies to the parent.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZUoOZ_3d7OxdGh8yk-:-MZYcVlPCTCyCcvAIgPK:b-eu99mz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c54e8c1ab98862543aa7d9f742c0ae97e746c5f7/src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> TEMPORARILY
> ```
This name seems a little weird because it's still a terminal (i.e. non-temporary) state for this attempt. Non-blocking since I can't immediately come up with a better name to describe that the "temporary" part applies to the parent.
</blockquote></details>

Yeah, it's a little weird. It wants to say "the attempt failed but a new attempt should be created". `FAILED_WITH_TRANSIENT_ERROR`? `RETRIABLY_FAILED`?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZUoOZ_3d7OxdGh8yk-:-MZYjgc9AnzQrQCIB2di:b-g6701z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c54e8c1ab98862543aa7d9f742c0ae97e746c5f7/src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto#L53)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yeah, it's a little weird. It wants to say "the attempt failed but a new attempt should be created". `FAILED_WITH_TRANSIENT_ERROR`? `RETRIABLY_FAILED`?
</blockquote></details>

Maybe `FAILED_REATTEMPTABLE` to utilize the fact that these are called attempts to imply that you can't retry *this* attempt, but can make a new one?

Or perhaps the states being `FAILED` and `FAILED_STEP` where the latter implies that it also results in the parent step being put into a failed state?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto, line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZUoOZ_3d7OxdGh8yk-:-MZYmfk3DkCrdIpFva1o:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c54e8c1ab98862543aa7d9f742c0ae97e746c5f7/src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Maybe `FAILED_REATTEMPTABLE` to utilize the fact that these are called attempts to imply that you can't retry *this* attempt, but can make a new one?

Or perhaps the states being `FAILED` and `FAILED_STEP` where the latter implies that it also results in the parent step being put into a failed state?
</blockquote></details>

Done

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto, line 52 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZZNXbfBlcYqrgKeTCe:-MZZNXbfBlcYqrgKeTCf:bor4wio) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9ab5b33e7b4ad4d94c2c9df749aff910b8aff561/src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto#L52)):*
> ```protobuf
> 
>     // The attempt has failed but the `ExchangeStep` can be retried.
>     // Terminal state.
> ```

This is not terminal state for the Step though? The step can be retried at this point with different attempt?
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZZOHkI3JfMJ_1QvuuL:-MZZOHkI3JfMJ_1QvuuM:bbe4pvu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9ab5b33e7b4ad4d94c2c9df749aff910b8aff561/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L62)):*
> ```protobuf
> message FindReadyExchangeStepResponse {
>   // If unset, there was no ready `ExchangeStep`.
>   ExchangeStep exchange_step = 1;
> ```

So this will return an arbitrary ExchangeStep in READY state or is there any order we want?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto, line 52 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZZNXbfBlcYqrgKeTCe:-MZZPCDI2RKDN6absgGH:b7u03hh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9ab5b33e7b4ad4d94c2c9df749aff910b8aff561/src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempt.proto#L52)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

This is not terminal state for the Step though? The step can be retried at this point with different attempt?
</blockquote></details>

Correct
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZZOHkI3JfMJ_1QvuuL:-MZZPEO0-rQhKtuKaxvc:bt8v7pa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9ab5b33e7b4ad4d94c2c9df749aff910b8aff561/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L62)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

So this will return an arbitrary ExchangeStep in READY state or is there any order we want?
</blockquote></details>

It will be arbitrary. I don't think we need to care about the order.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto, line 60 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZmUf3q0RTreDDQPojM:-MZmUf3q0RTreDDQPojN:bbdeuw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9ab5b33e7b4ad4d94c2c9df749aff910b8aff561/src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto#L60)):*
> ```protobuf
>     STATE_UNSPECIFIED = 0;
> 
>     // Some predecessor ExchangeStep is not in state SUCCEEDED.
> ```

Looking at the standard Airflow tasks below

`SUCCESS, RUNNING, FAILED, UPSTREAM_FAILED, SKIPPED, UP_FOR_RETRY, UP_FOR_RESCHEDULE, QUEUED, NONE, SCHEDULED`

Are you sure you don't want to be clearer with an up_for_retry state? Someone could look at the number of retries and see that its in ready state but that is less clear to some future maintainer.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto, line 60 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZmUf3q0RTreDDQPojM:-MZnJ8-t5fRN9WjCQBkH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/9ab5b33e7b4ad4d94c2c9df749aff910b8aff561/src/main/proto/wfa/measurement/api/v2alpha/exchange_step.proto#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Looking at the standard Airflow tasks below

`SUCCESS, RUNNING, FAILED, UPSTREAM_FAILED, SKIPPED, UP_FOR_RETRY, UP_FOR_RESCHEDULE, QUEUED, NONE, SCHEDULED`

Are you sure you don't want to be clearer with an up_for_retry state? Someone could look at the number of retries and see that its in ready state but that is less clear to some future maintainer.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 40 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZo9vt11m-SBLR_l7qb:-MZo9vt11m-SBLR_l7qc:b-4zv9y3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c4f3cccf2ff326315f7cdb2d10b3c2ce96628381/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L40)):*
> ```protobuf
>   // Since this is expected, normal behavior, it does NOT return a NOT_FOUND
>   // error.
>   rpc FindReadyExchangeStep(FindReadyExchangeStepRequest)
> ```

(I'm assuming a multiple workers model)
How does the worker communicate that it started working on a particular exchange step?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

**Review by efoxepstein — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 40 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/21#-MZo9vt11m-SBLR_l7qb:-MZoEagI75H375MuPJXl:b6gtvv2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c4f3cccf2ff326315f7cdb2d10b3c2ce96628381/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

(I'm assuming a multiple workers model)
How does the worker communicate that it started working on a particular exchange step?
</blockquote></details>

(Discussed on Slack.)

**Pull request merged**
