### PR TITLE
Add external Event Group Metadata API proto files

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93)

### CODE REVIEW

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-Myn90T1D7w4MNl2MmFx:-Myn90T1D7w4MNl2MmFy:bg1c6vk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L26)):*
> ```protobuf
> option java_outer_classname = "EventGroupMetadataDescriptorProto";
> 
> // The metadata message descriptor of an `EventGroup`. This metadata is used to
> ```

For the second sentence, it would be more accurate to say something like "This descriptor is used to parse the contents of an `EventGroup.Metadata` message."

On that note, the `EventGroup.Metadata` message also needs to be updated per your design doc. You could do that in this PR or in another.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-Myn8U2IDB3wG5gUdBzQ:-Myn8U2IDB3wG5gUdBzR:b-jam89o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L29)):*
> ```protobuf
> // describe the contents of an `EventGroup` without needing a direct dependency
> // on it.
> message EventGroupMetadataDescriptor {
> ```

All resources should have a `name` field (preferably as field 1).
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MynASkT2kL694G9qms-:-MynASkT2kL694G9qms0:b-mdqbc6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L35)):*
> ```protobuf
>   };
> 
>   // FileDescriptorSet of the metadata proto message.
> ```

I think we should be clear that this includes the file descriptor of the message's proto file, as well as the transitive closure of all imported proto files.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MynBAwm0NxtqZoyOw-p:-MynBAwm0NxtqZoyOw-q:bqx159o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L43)):*
> ```protobuf
>   // If set, this value must be unique among `EventGroupMetadataDescriptor`s for
>   // the parent `DataProvider`.
>   string external_reference_id = 2;
> ```

I don't recall seeing this field in the design doc, and I'm not sure I know of a use case. Were you copying this from event group? I think it makes sense for an event group, because an `EventGroup` resource is a representation of a campaign in an EDP's system, so the reference ID would point to a row in a database most likely.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MynL2LqB-I0ghxsx1Sc:-MynL2LqB-I0ghxsx1Sd:bxf24uh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto#L62)):*
> ```protobuf
>   // The `EventGroupMetadataDescriptor` to create. Required.
>   //
>   // The `key` field will be ignored, and the system will assign an ID. Results
> ```

I think `key` should be `name`. I see this in other services, too...it's probably an artifact of some past refactor.



_Code quote:_
```protobuf
key
```

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-Myn8U2IDB3wG5gUdBzQ:-Mz19QF_3oDiOQ00G-7R:b5d038l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L29)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

All resources should have a `name` field (preferably as field 1).
</blockquote></details>

Is this `name` field referring to the external ID? I'm unclear on how this translates to the [internal message](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptor.proto?L24:9).
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MynBAwm0NxtqZoyOw-p:-Mz19ve57EvnHI_70GiB:b-2kk6bx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L43)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I don't recall seeing this field in the design doc, and I'm not sure I know of a use case. Were you copying this from event group? I think it makes sense for an event group, because an `EventGroup` resource is a representation of a campaign in an EDP's system, so the reference ID would point to a row in a database most likely.
</blockquote></details>

I had intended for this to map to the `external_event_group_metadata_descriptor_id` internal field -- how will the external id be passed in otherwise?

**Review by robinsons — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-Myn8U2IDB3wG5gUdBzQ:-MzGBXbhEgs8A3YUYTtr:b-qc2540) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L29)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Is this `name` field referring to the external ID? I'm unclear on how this translates to the [internal message](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/proto/wfa/measurement/internal/kingdom/event_group_metadata_descriptor.proto?L24:9).
</blockquote></details>

The `name` is a resource name string [1] that has the format indicated by the `(google.api.resource).pattern` attribute. In our public APIs, resource names follow a pattern like `dataProviders/abc/eventGroupMetadataDescriptors/def` where `abc` and `def` are the identifiers. We use the helper classes `ApiId` and `ExternalId` [2] to convert between API IDs (strings) and external IDs (longs). If you look at the ID classes, you'll see that the API ID is just a base64 encoding of the external ID. If you look at any of our public API service implementations, you should be able to see the API ID-to-external ID conversion in action.

In short, the resource name bundles the resource type and all of its unique identifiers into a single field.

[1] https://google.aip.dev/122
[2] https://sourcegraph.com/github.com/world-federation-of-advertisers/common-jvm@8b3785cde4252b27fa189efa03fa2a922a600c99/-/blob/src/main/kotlin/org/wfanet/measurement/common/identity/Identifiers.kt
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MynBAwm0NxtqZoyOw-p:-MzGFf0_Dcs1s0aRpHf3:b6jcjrb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L43)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I had intended for this to map to the `external_event_group_metadata_descriptor_id` internal field -- how will the external id be passed in otherwise?
</blockquote></details>

See above comment about the `name` field.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-Myn90T1D7w4MNl2MmFx:-MzG3w8u1DX0Q0YWOpYW:b-beqkme) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L26)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

For the second sentence, it would be more accurate to say something like "This descriptor is used to parse the contents of an `EventGroup.Metadata` message."

On that note, the `EventGroup.Metadata` message also needs to be updated per your design doc. You could do that in this PR or in another.
</blockquote></details>

Thanks for the catch. Added to this PR.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-Myn8U2IDB3wG5gUdBzQ:-MzGcYlz8c7JCVhBgGwm:b-ijhokc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L29)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

The `name` is a resource name string [1] that has the format indicated by the `(google.api.resource).pattern` attribute. In our public APIs, resource names follow a pattern like `dataProviders/abc/eventGroupMetadataDescriptors/def` where `abc` and `def` are the identifiers. We use the helper classes `ApiId` and `ExternalId` [2] to convert between API IDs (strings) and external IDs (longs). If you look at the ID classes, you'll see that the API ID is just a base64 encoding of the external ID. If you look at any of our public API service implementations, you should be able to see the API ID-to-external ID conversion in action.

In short, the resource name bundles the resource type and all of its unique identifiers into a single field.

[1] https://google.aip.dev/122
[2] https://sourcegraph.com/github.com/world-federation-of-advertisers/common-jvm@8b3785cde4252b27fa189efa03fa2a922a600c99/-/blob/src/main/kotlin/org/wfanet/measurement/common/identity/Identifiers.kt
</blockquote></details>

Thanks for the detailed explanation! This makes sense -- updated.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MynASkT2kL694G9qms-:-MzG4kRn780DYsWwRDX7:bxye5kg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L35)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I think we should be clear that this includes the file descriptor of the message's proto file, as well as the transitive closure of all imported proto files.
</blockquote></details>

Updated -- your phrasing seemed like a complete description so I went ahead and used it.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MynBAwm0NxtqZoyOw-p:-MzGcfRL178woAEE4iwy:bss4a2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptor.proto#L43)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

See above comment about the `name` field.
</blockquote></details>

Removed.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MynL2LqB-I0ghxsx1Sc:-MzGcnmg613NKXciKaCJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b490d050e970e2ff7392459f6159717a50779e58/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto#L62)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I think `key` should be `name`. I see this in other services, too...it's probably an artifact of some past refactor.
</blockquote></details>

Done.

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group.proto, line 78 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MzHCOpvCYTOUM-Nb3qR:-MzHCOpvCYTOUM-Nb3qS:bbzm1y3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f18627f4dc6a79348e3eb7c7451acedcfedcdbc4/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L78)):*
> ```protobuf
>   message Metadata {
>     // The resource name of the metadata descriptor.
>     string descriptor_name = 1;
> ```

Should probably be `event_group_metadata_descriptor` and have the `(google.api.resource_reference).type` annotation. Check out one of the other fields, like `measurement_consumer`, as an example.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group.proto, line 78 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/93#-MzHCOpvCYTOUM-Nb3qR:-MzHGC6A3dD60iojK450:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f18627f4dc6a79348e3eb7c7451acedcfedcdbc4/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L78)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Should probably be `event_group_metadata_descriptor` and have the `(google.api.resource_reference).type` annotation. Check out one of the other fields, like `measurement_consumer`, as an example.
</blockquote></details>

Done.

**Pull request merged**
