### PR TITLE
add generate cipher exchange steps

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/56)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/56)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/56#-Mkni9hG8S7R4K_CW2vg:-Mkni9hG8S7R4K_CW2vh:b-56gtn7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/6358c82ccea83d0775a6ddcaa552153495bf2f53/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L48)):*
> ```protobuf
>   // Config needed by parties before certain exchange steps occur.
>   message ExchangeConfig {
>       int32 num_shards = 1;
> ```

How do you feel about inlining this into the steps that need it? We pass the `ExchangeWorkflow.Step` around a lot in code and it would be nice if it contained all the parameters that it needs.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/56)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/56#-Mkni9hG8S7R4K_CW2vg:-Mko0OeTDjqkTnHSsDOm:brgyltw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/6358c82ccea83d0775a6ddcaa552153495bf2f53/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How do you feel about inlining this into the steps that need it? We pass the `ExchangeWorkflow.Step` around a lot in code and it would be nice if it contained all the parameters that it needs.
</blockquote></details>

thats actually how I did it at first. I was thinking since the parameters need to be equal I would separate. But I see your point. Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
