### PR TITLE
Removed comment for VID wraparound

### PR DESCRIPTION
**Pull request by iverson52000**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/99)

### CODE REVIEW

**Review by uakyol — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/99)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by uakyol — CHANGES_REQUESTED** [review]
Actually, I am a bit confused. What happens now if start + width is larger than 1? In the code you wrote here: https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/517 it seems that we just allow the range to go above 1. Is that intentional?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/99#-:-N-5N3PI0FJr_wH5cBEb:bd2gofs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by iverson52000 — COMMENTED** [review]
> What happens now if start + width is larger than 1
In my understanding we are just removing the wraparound logic here. For case start + width > 1, I have to clarify with Matt how do we handle it

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/99#-:-N-989YBCKc3WVrJOeoj:bayfiwo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by uakyol — CHANGES_REQUESTED** [review]
Albert it seems what you id is correct. We just need to document that start + width cannot be larger than 1 here. 
Would you mind just updating the comment here?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/99#-:-N-P9uG5119hMf-7scXG:b-vlxgzn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Comment by iverson52000** [comment]
Sure will double check with Matt in our 1-1 today

**Review by uakyol — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/99)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Pull request merged**
