### PR TITLE
Use resource names instead of Key messages in the v2alpha API.

### PR DESCRIPTION
**Pull request by SanjayVas**
The use of Key messages made it difficult to define resource types that could have more than one possible parent type, such as Certificate and PublicKey. Additionally, this removes a deviation from the AIPs (see https://google.aip.dev/122).

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29#-MaetOCD0XkTz5GdpelG:-MaetNLV1BxHccs6f-i1:b-vzsp0w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0faa513acb8f098cdb358dbfc31e7776d3221c8e/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L64)):*
> ```protobuf
> message DataProviderList {
>   repeated string data_provider = 1 [
>     (google.api.resource_reference) = { type: "halo.wfanet.org/DataProvider" }
> ```

Does this more concise syntax work? `(google.api.resource_reference).type = "halo.wfanet.org/DataProvider"`

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29)* status: 12 of 32 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @kungfucraig)

___
*[src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29#-MaetOCD0XkTz5GdpelG:-Maf7zqN-hkbL3sUG3kW:bg4jmcy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0faa513acb8f098cdb358dbfc31e7776d3221c8e/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L64)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does this more concise syntax work? `(google.api.resource_reference).type = "halo.wfanet.org/DataProvider"`
</blockquote></details>

Done.

There are potential cases where we also may need to set an additional field in `resource_reference`, but we don't have any of those yet.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 20 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempts_service.proto, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29#-MaisOuvAYkMMmRaD6jC:-MaisOuvAYkMMmRaD6jD:blaq7fk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/523ecb6cb33fee0265619873fb978451e89c37d8/src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempts_service.proto#L54)):*
> ```protobuf
>   // Resource name.
>   string name = 1 [(google.api.resource_reference).type =
>                        "halo.wfanet.org/ExchangeStepAttempt"];
> ```

It feels a little inconsistent that sometimes there's a line break after the `=` and sometimes the whole `[ ... ]` is on its own line.

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @kungfucraig)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempts_service.proto, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29#-MaisOuvAYkMMmRaD6jC:-Maj0-qU2O8p7GPoGMzu:b9ur17p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/523ecb6cb33fee0265619873fb978451e89c37d8/src/main/proto/wfa/measurement/api/v2alpha/exchange_step_attempts_service.proto#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It feels a little inconsistent that sometimes there's a line break after the `=` and sometimes the whole `[ ... ]` is on its own line.
</blockquote></details>

I agree. Unfortunately, this is what clang-format outputs, regardless of how the input is formatted.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by zachcwc — APPROVED** [review]
> Reviewed 12 of 32 files at r1, 19 of 20 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @kungfucraig, and @oliver-amzn)

**Review by corbantek — APPROVED** [review]

**Pull request merged**
