### PR TITLE
Define Certificates service with methods for interacting with revocation state.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/30)

### CODE REVIEW

**Comment by SanjayVas** [comment]
This is intended to be merged into main after the parent PR #29. It's related to world-federation-of-advertisers/cross-media-measurement#78.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/30)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/certificates_service.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/30#-Maji3ma0cwVxVa1E8gj:-Maji3ma0cwVxVa1E8gk:b-g234rm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4ff58eaae93852ef04d57bc96738da0199fe7fac/src/main/proto/wfa/measurement/api/v2alpha/certificates_service.proto#L29)):*
> ```protobuf
> service Certificates {
>   // Creates (adds) a `Certificate`.
>   rpc CreateCertificate(CreateCertificateRequest) returns (Certificate) {}
> ```

OOC does clang-tidy let you use a semi-colon instead of `{}`? Seems a little clearer to me.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/30)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @kungfucraig)

___
*[src/main/proto/wfa/measurement/api/v2alpha/certificates_service.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/30#-Maji3ma0cwVxVa1E8gj:-Majpg4Z4nu4Oz_TMVCF:bhajhb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4ff58eaae93852ef04d57bc96738da0199fe7fac/src/main/proto/wfa/measurement/api/v2alpha/certificates_service.proto#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OOC does clang-tidy let you use a semi-colon instead of `{}`? Seems a little clearer to me.
</blockquote></details>

clang-format allows it. The `{}` syntax was copied from the gRPC and AIP docs. The brace syntax is needed if you're adding annotations to the method, which are needed for APIs that are served over HTTP. We should also add the other non-http API annotations such as `field_behavior`, but that can be done later.

**Review by zachcwc — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/30)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @efoxepstein, @kungfucraig, and @oliver-amzn)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek, @kungfucraig, and @oliver-amzn)

**Review by corbantek — APPROVED** [review]

**Pull request merged**
