### PR TITLE
Add sequence diagrams for more flows.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/125)

**Comment by mariolamassaavedra** [comment]
@SanjayVas just to clarify when does Create account (new_mc_account_creation_flow.png) happens? or is it not relevant and should focus only on "Generation a MC creation token" and "creating a MC"?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/125)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mariolamassaavedra)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/125#-NR2rm9v6NLLerg7lWg4:-NR4ODsO1J75ZKMFadQA:b-b880k2) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note how "Creating a MeasurementConsumer" mentions already having obtained `Account` credentials? The Kingdom operator needs to create an Account for the MC owner. The MC owner then needs to activate that Account. Then the MC owner can follow the authentication flow to obtain the Account credentials necessary to perform operations that require those credentials, such as creating a `MeasurementConsumer` resource.

These are broken down into separate flows since you don't necessarily need to do them all in a single session. An MC owner may also need to repeat the auth flow if their credentials have expired, so basically before any operation that needs those credentials. Other such operations include creating/deleting API keys.
</blockquote></details>

For the context of tnis PR, I didn't bother making a page for that diagram since it's a small one that doesn't need additional explanation.

___

**Review by mariolamassaavedra — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/125)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
