### PR TITLE
Add a `parent` field to ClaimReadyExchangeStepRequest.

### PR DESCRIPTION
**Pull request by SanjayVas**
The method operates on the recurringExchanges resource collection.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/142)

**Comment by SanjayVas** [comment]
Depends on #180

**Comment by SanjayVas** [comment]
CC @kungfucraig for API changes

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/142)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
