### PR TITLE
Add Reach-Only Liquid Legions protocol into protocol_config

### PR DESCRIPTION
**Pull request by renjiezh**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @ple13)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @ple13, and @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157#-N_9e8lK1r_93pTUKq8-:-N_9e8lK1r_93pTUKq80:b-dkyp7z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b14f229ed90b369bdfb454ba87d75cd048b45438/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L96)):*
> ```proto
>   message ReachOnlyLiquidLegionsV2 {
>     // Parameters for sketch.
>     LiquidLegionsSketchParams sketch_params = 1
> ```

This isn't quite what we want here. Specifically the sampling indicator is not required for reach only. We could do one of two things: 1) document that it is not required or 2) (my preference) create a reach only SketchParams message.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, @ple13, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157#-N_9e8lK1r_93pTUKq8-:-N_A7aPT6ItfrzgP92Y4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b14f229ed90b369bdfb454ba87d75cd048b45438/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L96)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This isn't quite what we want here. Specifically the sampling indicator is not required for reach only. We could do one of two things: 1) document that it is not required or 2) (my preference) create a reach only SketchParams message.
</blockquote></details>

Done.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157#-N_9e8lK1r_93pTUKq8-:-N_APlb-DeD-3cOCjrnG:bct1ydf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b14f229ed90b369bdfb454ba87d75cd048b45438/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L96)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see a code change.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, @ple13, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157#-N_9e8lK1r_93pTUKq8-:-N_AQ04M1Mgv2vfdgnav:bhp9zvh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b14f229ed90b369bdfb454ba87d75cd048b45438/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L96)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't see a code change.
</blockquote></details>

Could you please try to refresh the page and select the latest commit. I did rebase that might break the showing.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @ple13, and @renjiezh)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157#-N_9e8lK1r_93pTUKq8-:-N_AQeHe1b5r2axLkgXM:b-dz2fq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/b14f229ed90b369bdfb454ba87d75cd048b45438/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L96)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Could you please try to refresh the page and select the latest commit. I did rebase that might break the showing.
</blockquote></details>

I see it now.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 116 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157#-N_ARDtbB7_0TR4QhwVR:-N_ARDtbB7_0TR4QhwVS:byv4dqz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/278cd655592ca1297ab33075ad06f6354a35cfb1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L116)):*
> ```proto
> 
>   // Configuration for the specific protocol. Required. Immutable.
>   oneof protocol {
> ```

If we're going to delete this it should be as part of a separate PR. Remember that we try to abide by the single change per PR principle.

**Review by renjiezh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, and @ple13)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto` line 116 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157#-N_ARDtbB7_0TR4QhwVR:-N_Aq6S96nfuNMQKA-Bx:b-whwz66) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/278cd655592ca1297ab33075ad06f6354a35cfb1/src/main/proto/wfa/measurement/api/v2alpha/protocol_config.proto#L116)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

If we're going to delete this it should be as part of a separate PR. Remember that we try to abide by the single change per PR principle.
</blockquote></details>

Done. Reverted.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, and @ple13)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @ple13)

**Review by ple13 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
