### PR TITLE
Add FileSystem to ExchangeWorkflow.StorageType

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jonmolle, @stevenwarejones, and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73#-Mold5Fb1zNmv891zx1-:-Mold5FcAQiFYEw_3LF4:biwvyop) (no related file):*
Why is this necessary?

---

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73#-Mold5Fb1zNmv891zx1-:-MoldqrOAZIdux8-EeF1:byrw39s) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is this necessary?
</blockquote></details>

Seems like we introduced exchangeIdentifiers.storageType in ExchangeWorkflow proto. So we are validating storage type here;
https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cfdabecfe157a6486aa2a199dfca6bc1d47bcc89/src/main/kotlin/org/wfanet/panelmatch/client/storage/SharedStorageSelector.kt#L66

causing crash because storage details has FILE https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cfdabecfe157a6486aa2a199dfca6bc1d47bcc89/src/main/proto/wfa/panelmatch/client/storage/storage_details.proto#L76

---

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle, @stevenwarejones, and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73#-Mold5Fb1zNmv891zx1-:-Molf5UsCDgnEdpUu6st:b-pn6w9i) (no related file):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Seems like we introduced exchangeIdentifiers.storageType in ExchangeWorkflow proto. So we are validating storage type here;
https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cfdabecfe157a6486aa2a199dfca6bc1d47bcc89/src/main/kotlin/org/wfanet/panelmatch/client/storage/SharedStorageSelector.kt#L66

causing crash because storage details has FILE https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cfdabecfe157a6486aa2a199dfca6bc1d47bcc89/src/main/proto/wfa/panelmatch/client/storage/storage_details.proto#L76
</blockquote></details>

Thanks. Can you add a comment saying that this is to support testing and likely shouldn't be used in production?

---

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73#-MooEKEu87hwJORwlO6Z:-MooEKEvDo7MEQCGWnkd:bdnvx0o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0c52fa75c5e4c4abf76f31fb4d2764b84095c651/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L45)):*
> ```protobuf
>     AMAZON_S3 = 2;
>     // This is to support testing and likely should NOT be used in production.
>     FILE_SYSTEM = 3;
> ```

can this just get mapped to the unknown storage client for testing?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73#-MooEKEu87hwJORwlO6Z:-MooTYNU42wHkvUu1Hzr:b-9g8yry) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0c52fa75c5e4c4abf76f31fb4d2764b84095c651/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L45)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can this just get mapped to the unknown storage client for testing?
</blockquote></details>

Yes, but we already have PlatformCase.FILE_SYSTEM and InMemoryStorageClient, etc. implemented. 
 I strongly believe it would be compatible everywhere in the code if we use FILE_SYSTEM here.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/73#-MooEKEu87hwJORwlO6Z:-Mq_0-8VD3G72NL7BUgX:b-j0ccuz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/0c52fa75c5e4c4abf76f31fb4d2764b84095c651/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L45)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Yes, but we already have PlatformCase.FILE_SYSTEM and InMemoryStorageClient, etc. implemented. 
 I strongly believe it would be compatible everywhere in the code if we use FILE_SYSTEM here.
</blockquote></details>

i'm not sure I understand. If its for testing, they can just use UNKNOWN. If we want to include testing sources explcitly, we should include InMemory and FileSystem

**Pull request closed without merging**
