### PR TITLE
Update public API for Event Groups.

### PR DESCRIPTION
**Pull request by robinsons**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @robinsons, @stevenwarejones, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77#-MprNQTVCcl1aNIMGwtD:-MprNQTVCcl1aNIMGwtE:bkef48a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4d409158b02c39dd33398ab30bee6f6b83cb4c1d/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L37)):*
> ```protobuf
>   string name = 1;
> 
>   // Resource name of the `MeasurementConsumer` associated with this
> ```

Add `Required` and/or `Immutable` comments to the appropriate fields. e.g. this field should have `Required. Immutable`.

The immutability part is especially important to know when we have an Update method.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group.proto, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77#-MprLLf51jdUfmJ6Qn4R:-MprLLf51jdUfmJ6Qn4S:b-qiex8m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4d409158b02c39dd33398ab30bee6f6b83cb4c1d/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L65)):*
> ```
> class name
> ```
nit: "class" isn't a term used by protobuf. Maybe "fully-qualified protobuf message type"?
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group.proto, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77#-MprRpJX0kNyV96nT4H_:-MprRpJX0kNyV96nT4Ha:bly23sn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4d409158b02c39dd33398ab30bee6f6b83cb4c1d/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L81)):*
> ```protobuf
>   // verified using `data_provider_certificate`. The encryption uses
>   // `measurement_consumer_public_key` as the recipient public key.
>   bytes encrypted_metadata = 9;
> ```

Do we need this to be signed as well as encrypted?

My concern is that we're expecting our certificates to have pretty short lifetimes (~2 weeks). We've been okay with certificates for a Measurement expiring as we don't tend to care about that verification once the Measurement is complete, but Event Group metadata is likely to be accessed on a longer time horizon. While the signature of the recipient public key only needs to be verified at metadata encryption time, the signature of the metadata itself would need to be verified on each read. This means that when the EDP rotates their certificate, they have to update every EventGroup's metadata.

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77#-MprNQTVCcl1aNIMGwtD:-Mprn_CrAemLmAhqMzs1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4d409158b02c39dd33398ab30bee6f6b83cb4c1d/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add `Required` and/or `Immutable` comments to the appropriate fields. e.g. this field should have `Required. Immutable`.

The immutability part is especially important to know when we have an Update method.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group.proto, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77#-MprRpJX0kNyV96nT4H_:-Mprnebn9Cy3kqLcDrhZ:b-ccr4vv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/4d409158b02c39dd33398ab30bee6f6b83cb4c1d/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L81)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we need this to be signed as well as encrypted?

My concern is that we're expecting our certificates to have pretty short lifetimes (~2 weeks). We've been okay with certificates for a Measurement expiring as we don't tend to care about that verification once the Measurement is complete, but Event Group metadata is likely to be accessed on a longer time horizon. While the signature of the recipient public key only needs to be verified at metadata encryption time, the signature of the metadata itself would need to be verified on each read. This means that when the EDP rotates their certificate, they have to update every EventGroup's metadata.
</blockquote></details>

Thanks for pointing that out. I've removed the bit about signing.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh, @stevenwarejones, and @uakyol)

**Review by chipingyeh — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)

**Review by duliomatos1 — APPROVED** [review]
lgtm

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77#-:-MqGHCFYDJO81sZZrj39:bb7k0qh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)

**Review by robinsons — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)

**Pull request merged**
