### PR TITLE
Add /ExchangeSteps.ListExchangeSteps 

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 3 unresolved discussions (waiting on @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MngzRGe2ezgfIcj0tLk:-MngzRGe2ezgfIcj0tLl:b-9me2ym) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d56cfe9c92ec632b394967cf550ccebc2f213565/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L41)):*
> ```protobuf
>       returns (ClaimReadyExchangeStepResponse);
> 
>   // Lists `ExchangeStep`s for the parent `RecurringExchange`.
> ```

Maybe remove "for the parent RecurringExchange" because we can support a wildcard query (list all my ExchangeSteps across all my RecurringExchanges)
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MngzgW-5sgwaI8SoahP:-MngzgW-5sgwaI8SoahQ:bia9d8y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d56cfe9c92ec632b394967cf550ccebc2f213565/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L78)):*
> ```protobuf
> // Request message for `ListExchangeSteps` method.
> message ListExchangeStepsRequest {
>   // Resource name of the parent `RecurringExchange`. Required.
> ```

Remove `Required.`? I think we can support lists across multiple RecurringExchanges if we want to.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-Mnh-9G23PoB2eYKL98G:-Mnh-9G38DR1uAG7OMVC:bw0iqqx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d56cfe9c92ec632b394967cf550ccebc2f213565/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L116)):*
> ```protobuf
>   // ListExchangeStepsRequest
>   repeated ExchangeStep exchange_step = 1;
>   // A token, which can be sent as `page_token` to retrieve the next page.
> ```

Nit: add a blank line above this

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @yunyeng)

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 94 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnhnoWlDHLdoveML8FK:-MnhnoWm4ABxP4_6WbFe:b-ypvmam) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L94)):*
> ```protobuf
>   // `ListExchangeStepsRequest` must match the call that provided the
>   // page token.
>   string page_token = 3;
> ```

why not just call this offset?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 94 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnhnoWlDHLdoveML8FK:-Mnhs9pZ3bqJFctigPEh:bs27isi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L94)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not just call this offset?
</blockquote></details>

https://google.aip.dev/132 -- these are standard names. Offset is considered brittle

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 94 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnhnoWlDHLdoveML8FK:-MnkTc570b_F8ohomhyi:b-yp2ovv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L94)):*
> https://google.aip.dev/132
gtk

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlAtZq4Cm-hpuCLdmU:-MnlAtZq4Cm-hpuCLdmV:b-o3x1f4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L102)):*
> ```
> // Party name. Required.
> ```

From https://google.aip.dev/132:
> The request message **must not** contain any other required fields, and should not contain other optional fields except those described in this or another AIP.

The entire filter should be optional.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlAtZq4Cm-hpuCLdmU:-MnlDjHv5j6PvEJfI_ie:bkwyfak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L102)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> // Party name. Required.
> ```

From https://google.aip.dev/132:
> The request message **must not** contain any other required fields, and should not contain other optional fields except those described in this or another AIP.

The entire filter should be optional.
</blockquote></details>

@sanjayvas, is the right behavior then for the API server to just set this filter itself from the principal in the context? Or just return unauthorized if the party isn't set?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 78 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnljGpn5nAWakFJhWQP:-MnljGpn5nAWakFJhWQQ:bu6bz9x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L78)):*
> ```protobuf
> // Request message for `ListExchangeSteps` method.
> message ListExchangeStepsRequest {
>   // Resource name of the parent `RecurringExchange`.
> ```

Please document that this can have any of the following 3 forms:

* recurringExchanges/{recurring_exchange}/exchanges/{exchange}
* dataProviders/{data_provider}/recurringExchanges/{recurring_exchange}/exchanges/{exchange}
* modelProviders/{data_provider}/recurringExchanges/{recurring_exchange}/exchanges/{exchange}

(Can you also add this documentation to the `Exchange` and `RecurringExchange` messages?)

For here only, you should say that {recurring_exchange} and {exchange} can be wildcards (subject to authorization).
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 80 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-Mnljhb2CTgzPPnHfTb9:-Mnljhb39LA026E08UIs:bt2e975) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L80)):*
> ```protobuf
>   // Resource name of the parent `RecurringExchange`.
>   string parent = 1 [(google.api.resource_reference).type =
>                          "halo.wfanet.org/RecurringExchange"];
> ```

The parent type should be `Exchange`
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 101 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlkZLFC3zBZ1m3o38z:-MnlkZLFC3zBZ1m3o39-:b-x33hsf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L101)):*
> ```protobuf
>     repeated google.type.Date exchange_dates = 1;
>     repeated ExchangeStep.State states = 2;
> ```

Please add two new filters:

```
repeated string recurring_exchange_data_providers
repeated string recurring_exchange_model_providers
```

to allow filtering the owners of the RecurringExchange
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlAtZq4Cm-hpuCLdmU:-MnlkIno6X3jW4N9Ehyi:b-mdrt9c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@sanjayvas, is the right behavior then for the API server to just set this filter itself from the principal in the context? Or just return unauthorized if the party isn't set?
</blockquote></details>

Discussed offline -- see other comments.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 78 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnljGpn5nAWakFJhWQP:-Mnlr5nh599JKd0ut673:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L78)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please document that this can have any of the following 3 forms:

* recurringExchanges/{recurring_exchange}/exchanges/{exchange}
* dataProviders/{data_provider}/recurringExchanges/{recurring_exchange}/exchanges/{exchange}
* modelProviders/{data_provider}/recurringExchanges/{recurring_exchange}/exchanges/{exchange}

(Can you also add this documentation to the `Exchange` and `RecurringExchange` messages?)

For here only, you should say that {recurring_exchange} and {exchange} can be wildcards (subject to authorization).
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 80 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-Mnljhb2CTgzPPnHfTb9:-Mnlr6_DDngtlprGC5-I:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L80)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The parent type should be `Exchange`
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 101 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlkZLFC3zBZ1m3o38z:-Mnlr87B7FwIF2LD8UE8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L101)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add two new filters:

```
repeated string recurring_exchange_data_providers
repeated string recurring_exchange_model_providers
```

to allow filtering the owners of the RecurringExchange
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 102 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlAtZq4Cm-hpuCLdmU:-Mnlr9K9B7VFjgbGsiUJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8188448c6d0a37b09fec826b24c6ce6a0a4033ae/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Discussed offline -- see other comments.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 80 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlxbDb0vjK8tasv-tQ:-MnlxbDb0vjK8tasv-tR:bfukwx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ab57b714af3bd78d5c8e342e5795e27a3b2621ea/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L80)):*
> ```
>   // recurringExchanges/{recurring_exchange}/exchanges/{exchange}
>   // dataProviders/{data_provider}/recurringExchanges/{recurring_exchange}/exchanges/{exchange}
>   // modelProviders/{data_provider}/recurringExchanges/{recurring_exchange}/exchanges/{exchange}
> ```
I believe the way you'd do this is to actually list the separate patterns in the resource type annotation for `halo.wfanet.org/Exchange`. Note that this means that those patterns must be valid everywhere, not just in this List method.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 90 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlxYDMDH64w5vAJB1U:-MnlxYDMDH64w5vAJB1V:b57csi0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ab57b714af3bd78d5c8e342e5795e27a3b2621ea/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L90)):*
> ```protobuf
>   // If unspecified, at most 50 `ExchangeStep`s will be returned.
>   // The maximum value is 1000; values above 1000 will be coerced to 1000.
>   int32 page_size = 4;
> ```

Missing some field numbers?

**Review by efoxepstein — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 80 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlxbDb0vjK8tasv-tQ:-Mnm5sTJ5LAYQX2QQoOY:b-ljk1hm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ab57b714af3bd78d5c8e342e5795e27a3b2621ea/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   // recurringExchanges/{recurring_exchange}/exchanges/{exchange}
>   // dataProviders/{data_provider}/recurringExchanges/{recurring_exchange}/exchanges/{exchange}
>   // modelProviders/{data_provider}/recurringExchanges/{recurring_exchange}/exchanges/{exchange}
> ```
I believe the way you'd do this is to actually list the separate patterns in the resource type annotation for `halo.wfanet.org/Exchange`. Note that this means that those patterns must be valid everywhere, not just in this List method.
</blockquote></details>

Unfortunately, we also likely then want to do this on RecurringExchange, ExchangeStep, and ExchangeStepAttempt resources too.

But that can happen in a different PR.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 80 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlxbDb0vjK8tasv-tQ:-MnmMUi5Bd1wZic_5k-1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ab57b714af3bd78d5c8e342e5795e27a3b2621ea/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L80)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Unfortunately, we also likely then want to do this on RecurringExchange, ExchangeStep, and ExchangeStepAttempt resources too.

But that can happen in a different PR.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 80 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlxbDb0vjK8tasv-tQ:-Mo01B0_-Mqm5neh7Xlw:b-kr1he6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ab57b714af3bd78d5c8e342e5795e27a3b2621ea/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L80)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

To clarify, was the idea to do Exchange in this PR and add patterns for the others in a later PR?

Add TODOs where relevant so it's clear what's planned.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto, line 80 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70#-MnlxbDb0vjK8tasv-tQ:-Mo0OH-B9JSWQ70unrBp:b94rxex) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ab57b714af3bd78d5c8e342e5795e27a3b2621ea/src/main/proto/wfa/measurement/api/v2alpha/exchange_steps_service.proto#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify, was the idea to do Exchange in this PR and add patterns for the others in a later PR?

Add TODOs where relevant so it's clear what's planned.
</blockquote></details>

Added multiple patterns in the exchange related protos.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

**Review by efoxepstein — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
