### PR TITLE
Add a population attribute annotation to the event field descriptor

### PR DESCRIPTION
**Pull request by kungfucraig**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/207)

**Review by SanjayVas — APPROVED** [review]
nit: PR title should be an imperative sentence ("Add" rather than "Adds"). See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/207#-:-NtrqJuS-PpendQ3Rvn5:b-xmsmpw)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto` line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/207#-NtrqbZu70WvsFU73RHq:-NtrqbZu70WvsFU73RHr:bbxwr9b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/41f12425f77f2387688c526ba1e99ee0ddf76406/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L42)):*
> ```proto
>   // a dimension of the output of a Virtual Person Model.
>   // For example, "age bucket" is usually a population field.
>   bool population_field = 3;
> ```

nit: maybe rename since the "field" part is already implied both by the fact that this is used in FieldOptions and the fact that the type is EventFieldDescriptor.

What we really want to indicate is whether this field is a population attribute.



_Suggestion:_
```proto
population_attribute
```

**Review by SanjayVas — COMMENTED** [review]
This is to document which fields the author of a population spec should fill in, as well as allow validation of the population spec.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/207#-:-NtvUmlw4HfCJxu8YsW1:b7ba7hm)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/207)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/207)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/207#-NtvKw0H6DdliDCSYsT9:-NtwivBGC0JUXUfVBDqu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/91a4634e523a818b305b4ddba13639590e9049e5/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`population`
</blockquote></details>

Done.

**Pull request merged**
