### PR TITLE
Add state field to event group definition

### PR DESCRIPTION
**Pull request by jcorilla**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)

### CODE REVIEW

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @SanjayVas)

**Review by kungfucraig — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117#-NN45DyDAubxK79vEYut:-NN45DyE5772RKK9YjcU:bik5e4) (no related file):*
Can you add the `show_deleted` field to the List and Get request messages as well?

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117#-NN4FXAr8q4DC0Y-dUJ5:-NN4FXAs1RmtAfJ-Fv2Y:b-8xmv2r) (no related file):*
Add some documentation on the Delete method indicating that while the EventGroup will remain in the DELETED state, all optional mutable fields will be cleared such that the operation is irreversible.

___
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group.proto` line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117#-NN4EuNFBn8EiTzo_1rM:-NN4EuNFBn8EiTzo_1rN:bi2w2o5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/c42c1282a5503d13b8878434248bd0223e45b6bb/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L97)):*
> ```protobuf
>     // The Event Group has been created
>     ACTIVE = 1;
>     // The Event Group has been deleted.
> ```

Document that this is a terminal state.

We have no intention of supporting undelete due to the fact that our delete operation makes some irreversible changes (e.g. wiping out any mutable optional fields).

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @jcorilla, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117#-NN8txWR9smZaDCJQn8h:-NN8txWR9smZaDCJQn8i:b-px4q3q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/16dc52d05a2aa29ea382597d405f7ac99a8a8c1e/src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto#L61)):*
> ```protobuf
> 
>   // Option to include deleted Event Groups.
>   bool show_deleted = 5;
> ```

how can we show deleted? I thought deleted meant these event groups were literally completely wiped from the db..

**Review by jcorilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117#-NN8txWR9smZaDCJQn8h:-NN9DU457wmMGThRhuFJ:bhe0eqg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/16dc52d05a2aa29ea382597d405f7ac99a8a8c1e/src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto#L61)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how can we show deleted? I thought deleted meant these event groups were literally completely wiped from the db..
</blockquote></details>

They wouldn't be completely wiped, they would only be soft deleted to prevent invalidating the reporting sets created with references to them.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @jcorilla, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117#-NN8txWR9smZaDCJQn8h:-NN9FKsm1iNV5zaQzTxt:b2ux7lo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/16dc52d05a2aa29ea382597d405f7ac99a8a8c1e/src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto#L61)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

They wouldn't be completely wiped, they would only be soft deleted to prevent invalidating the reporting sets created with references to them.
</blockquote></details>

event groups contain sensitive meta data - I don't think they can be soft deleted. They need to be hard deleted.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117#-NN8txWR9smZaDCJQn8h:-NN9IWOFCL85TkmsjuBO:brkofr2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/16dc52d05a2aa29ea382597d405f7ac99a8a8c1e/src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto#L61)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Once event groups are deleted, why do we need to reference their reporting sets anymore?
</blockquote></details>

The idea with the soft delete was to keep the event group, but to delete the contents of all of the columns with sensitive data. This way we don't unexpectedly orphan upstream references (e.g. reporting sets).

We could easily get into a situation where a reporting set is referencing a event group and the event group gets deleted, in which case the reporting set will become unusable and it will hard to discern why. With a soft deleted event group the reason will be obvious.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117#-NND-waF32CVXPXGNg-k:-NND-waF32CVXPXGNg-l:b34qg6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/16dc52d05a2aa29ea382597d405f7ac99a8a8c1e/src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto#L60)):*
> ```protobuf
>       [(google.api.resource_reference).type = "halo.wfanet.org/EventGroup"];
> 
>   // Option to include deleted Event Groups.
> ```

nit: phrasing

"Whether to include EventGroups in the DELETED state."



_Code quote:_
```protobuf
 Option to include deleted Event Groups.
```

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)

**Pull request merged**
