### PR TITLE
Add BatchGet service signature

### PR DESCRIPTION
**Pull request by chipingyeh**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105#-N3_aibf815LPZYTsWt2:-N3_aibf815LPZYTsWt3:b4oobbp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27a17e0a1d7298b8cdd873a41b89762b66f38ca5/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto#L89)):*
> ```protobuf
>              "halo.wfanet.org/EventGroupMetadataDescriptor"];
>   }
>   // Result filter.
> ```

BatchGet doesn't use a filter, but rather a list of resource names. See https://google.aip.dev/231



_Code quote:_
```protobuf
  // Result filter.
  Filter filter = 1;
```

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105#-N3_aibf815LPZYTsWt2:-N3_dLa45CZzwUYsGUHd:b-nd99tf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27a17e0a1d7298b8cdd873a41b89762b66f38ca5/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

BatchGet doesn't use a filter, but rather a list of resource names. See https://google.aip.dev/231
</blockquote></details>

Updated to `name`s. Do you think a `parent` field is needed, since this is primarily based on the resource name?

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105#-N3_aibf815LPZYTsWt2:-N3_kCJo8gtpyk9ZbZzd:b38okpl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27a17e0a1d7298b8cdd873a41b89762b66f38ca5/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto#L89)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Updated to `name`s. Do you think a `parent` field is needed, since this is primarily based on the resource name?
</blockquote></details>

It's not a top-level resource as it's under `DataProvider`. Therefore it should have a `parent` field. In general, we follow the AIPs except where noted in the [README](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/README.md).

Think of it from the REST perspective: the resource names tell you which resources to get and the `parent` field indicates the request URL path. It just happens to be that it isn't as critical for a gRPC-only API.

**Review by chipingyeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105#-N3_aibf815LPZYTsWt2:-N3_z64H6U_1X5t3f_MS:b-cty1g3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/27a17e0a1d7298b8cdd873a41b89762b66f38ca5/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata_descriptors_service.proto#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's not a top-level resource as it's under `DataProvider`. Therefore it should have a `parent` field. In general, we follow the AIPs except where noted in the [README](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/README.md).

Think of it from the REST perspective: the resource names tell you which resources to get and the `parent` field indicates the request URL path. It just happens to be that it isn't as critical for a gRPC-only API.

</blockquote></details>

That makes sense -- done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/105)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
