### PR TITLE
Add delete API for EventGroups

### PR DESCRIPTION
**Pull request by jcorilla**
Add delete eventgroup proto for external api

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/116)

### CODE REVIEW

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/116)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/116#-NM4owf8C21_2aqEOCrm:-NM4owf8C21_2aqEOCrn:b7oou7l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/08f05b45c633087add75de41d24916c864ce36f9/src/main/proto/wfa/measurement/api/v2alpha/event_groups_service.proto#L82)):*
> ```protobuf
> message DeleteEventGroupRequest {
>   // The `EventGroup` to delete. Required.
>   EventGroup event_group = 1;
> ```

Same as previous PR. :)

Use AIP delete request message convention. https://google.aip.dev/135#request-message

**Review by kungfucraig — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/116)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/116)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/116)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

**Review by kungfucraig — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
