### PR TITLE
Create protobuf message for Population bucket.

### PR DESCRIPTION
**Pull request by jojijac0b**
Creates population bucket proto message. This message type will be used to calculate populations of given demographics

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/201)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_bucket.proto` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/201#-NraxU5A-jxGYlY5aWRL:-NraxU5A-jxGYlY5aWRM:bwxn87v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/6ba9d8177b8b7c32035907942191b2a1e1203e52/src/main/proto/wfa/measurement/api/v2alpha/population_bucket.proto#L1)):*
> ```proto
> // Copyright 2024 The Cross-Media Measurement Authors
> ```

These won't be part of the public api since they will differ by market. I suggest creating a new folder call `populations` here and instead putting this pull request against cross-media-measurement.

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/201)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_bucket.proto` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/201#-NraxU5A-jxGYlY5aWRL:-Nrqb3n61uc1XbYZ_LI6:b-j4zq2z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/6ba9d8177b8b7c32035907942191b2a1e1203e52/src/main/proto/wfa/measurement/api/v2alpha/population_bucket.proto#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

These won't be part of the public api since they will differ by market. I suggest creating a new folder call `populations` here and instead putting this pull request against cross-media-measurement.
</blockquote></details>

I thought we agreed that for the test environment we'd reference TestEvent?

Also, can we just use the proto from my proposal? See: https://docs.google.com/document/d/1TwzhtRmRqD8Fu_ziamG8kuIDQ4h4g3AMeKVUT4ilkM4/edit?tab=t.0

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/201)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/population_bucket.proto` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/201#-NraxU5A-jxGYlY5aWRL:-Nrqc6E56YEpkOtMQMLx:b-xf14zx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/6ba9d8177b8b7c32035907942191b2a1e1203e52/src/main/proto/wfa/measurement/api/v2alpha/population_bucket.proto#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I thought we agreed that for the test environment we'd reference TestEvent?

Also, can we just use the proto from my proposal? See: https://docs.google.com/document/d/1TwzhtRmRqD8Fu_ziamG8kuIDQ4h4g3AMeKVUT4ilkM4/edit?tab=t.0
</blockquote></details>

Yes - 100% agree. This PR will get closed and Joji will use TestEvent instead.

**Comment by jojijac0b** [comment]
not needed

**Pull request closed without merging**
