### PR TITLE
Define ReplaceDataProviderRequiredDuchies method in public API

### PR DESCRIPTION
**Pull request by jojijac0b**
Define rpc method and request message for ReplaceDataProviderRequiredDuchies 

https://rally1.rallydev.com/#/604612930531d/iterationstatus?detail=%2Ftask%2F697342535629

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131#-NSlk9N4AI4w5HGg7_GU:-NSlk9N4AI4w5HGg7_GV:bqlvw8i) (no related file):*
Don't we need to add the `required_duchies` field to the `DataProvider` resource message first?

___
___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_providers_service.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131#-NSlkMeZ8QJ8JfxNOrfa:-NSlkMeZ8QJ8JfxNOrfb:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ad996c955b26d2efbf0f16128287ca418401ca05/src/main/proto/wfa/measurement/api/v2alpha/data_providers_service.proto#L37)):*
> ```protobuf
>   }
> 
>   // Replaces Duchy List
> ```

nit



_Suggestion:_
```protobuf
// Replaces the `required_duchies` field in a `DataProvider` resource.
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_providers_service.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131#-NSljRM13geqtnAwu5c7:-NSljRM13geqtnAwu5c8:bbt6e0k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ad996c955b26d2efbf0f16128287ca418401ca05/src/main/proto/wfa/measurement/api/v2alpha/data_providers_service.proto#L45)):*
> ```protobuf
> message ReplaceDataProviderRequiredDuchiesRequest {
>   fixed64 external_data_provider_id = 1;
>   repeated string required_external_duchy_ids = 2;
> ```

The public API uses resource names, not external IDs.

As [indicated in the README](https://github.com/world-federation-of-advertisers/cross-media-measurement-api#design), ensure that this API follows the AIPs.



_Code quote:_
```protobuf
  fixed64 external_data_provider_id = 1;
  repeated string required_external_duchy_ids = 2;
```

**Review by jojijac0b — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_providers_service.proto` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131#-NSljRM13geqtnAwu5c7:-NSrP1Z453YgZP6BWuWH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ad996c955b26d2efbf0f16128287ca418401ca05/src/main/proto/wfa/measurement/api/v2alpha/data_providers_service.proto#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The public API uses resource names, not external IDs.

As [indicated in the README](https://github.com/world-federation-of-advertisers/cross-media-measurement-api#design), ensure that this API follows the AIPs.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_providers_service.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131#-NSvXQ088uRoojUnPzbh:-NSvXQ088uRoojUnPzbi:b46y2th) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f4800e44bc1ffb3fc03058dff6417f13fb1c6e68/src/main/proto/wfa/measurement/api/v2alpha/data_providers_service.proto#L44)):*
> ```protobuf
> // Request message for ReplaceDataProviderDuchyList
> message ReplaceDataProviderRequiredDuchiesRequest {
>   string data_provider = 1
> ```

nit: Just call this field `name`, mirroring request messages for other methods that operate on a single resource.



_Code quote:_
```protobuf
data_provider
```

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @stevenwarejones)

**Review by jojijac0b — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131#-:-NSvnsRc3EkwyOhelGFr:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b)

**Review by jojijac0b — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/131#-:-NSwFXeECBnnZpTZSTxT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

**Pull request merged**
