### PR TITLE
Add CopyOptions to ExchangeWorkflow.CopyToSharedStorage

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @jonmolle)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52#-Mkcv6UW9WBv4nsL66zc:-Mkcv6UW9WBv4nsL66zd:bz75o85) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d40c00d8cf7926b0ce5e2bada60920eb370c7d7c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L77)):*
> ```protobuf
>     // for `CopyToSharedStorageStep`.
>     message CopyFromSharedStorageStep {
>       CopyOptions copy_options = 1;
> ```

they probably should have separate options. Will anyone copy from shared manifest storage?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @jonmolle)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52#-Mkcv6UW9WBv4nsL66zc:-MkcyYXH85w02MzCpjvR:bam706s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d40c00d8cf7926b0ce5e2bada60920eb370c7d7c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I was imagining the inputs to Beam would be copied from shared storage this way. For example, the encrypted queries: the MP would use CopyToSharedStorageStep to upload them, then the EDP would user CopyFromSharedStorageStep to download them.
</blockquote></details>

you wouldn't want to copy to private storage first?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jonmolle and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52#-Mkcv6UW9WBv4nsL66zc:-Mkd4J1IBf4D9hnV2U6q:b3l86xu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d40c00d8cf7926b0ce5e2bada60920eb370c7d7c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L77)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you wouldn't want to copy to private storage first?
</blockquote></details>

I'm a little confused, this is what I'm imagining:

1. MP runs some Beam task
2. MP runs CopyToSharedStorage
3. EDP runs CopyFromSharedStorage
4. EDP runs some Beam task

CopyToSharedStorage in step 2 requires the manifest to know which files to upload.
CopyFromSharedStorage in step 3 requires the manifest to know which files to download.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @jonmolle)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52#-Mkcv6UW9WBv4nsL66zc:-MkeCSX19LmHXwLGNYdN:b3mu9kc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d40c00d8cf7926b0ce5e2bada60920eb370c7d7c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm a little confused, this is what I'm imagining:

1. MP runs some Beam task
2. MP runs CopyToSharedStorage
3. EDP runs CopyFromSharedStorage
4. EDP runs some Beam task

CopyToSharedStorage in step 2 requires the manifest to know which files to upload.
CopyFromSharedStorage in step 3 requires the manifest to know which files to download.
</blockquote></details>

i'm a little concerned with introducing a beam dependency to sharing data. What if one party uses Beam and another party uses a custom Spark pipeline?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jonmolle and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52#-Mkcv6UW9WBv4nsL66zc:-MkeCqYo5bRJGVRVawVE:bcvbk0o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d40c00d8cf7926b0ce5e2bada60920eb370c7d7c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L77)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'm a little concerned with introducing a beam dependency to sharing data. What if one party uses Beam and another party uses a custom Spark pipeline?
</blockquote></details>

None of this is beam specific.

1. MP runs some task which produces a files "foo-0001-of-1234", "foo-0002-of-1234", ..., as well as a file "foo" with exact contents "foo-*-of-*".
2. MP runs CopyToSharedStorage
3. EDP runs CopyFromSharedStorage
4. EDP runs whatever they want that consumes the manifest file

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52#-Mkh8oYh731Xm90-NDdk:-Mkh8oYh731Xm90-NDdl:buh9tgk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d40c00d8cf7926b0ce5e2bada60920eb370c7d7c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L90)):*
> ```protobuf
>         // as a UTF-8 plaintext file containing a file spec/glob referencing
>         // other files that should be copied.
>         MANIFEST = 2;
> ```

Are we assuming that the manifest blob location is the same s3 location as the actual files listed in the manifest?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jonmolle and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52#-Mkh8oYh731Xm90-NDdk:-Mkh9QFcARNh2R4l1IXg:bfyn6ew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d40c00d8cf7926b0ce5e2bada60920eb370c7d7c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L90)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Are we assuming that the manifest blob location is the same s3 location as the actual files listed in the manifest?
</blockquote></details>

That's a great question. I'd say yes, let's say the manifest must contain a glob for files in the same directory (in other words, no slashes). WDYT about this? If OK, I'll add a comment here specifying that.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @jonmolle)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52#-Mkh8oYh731Xm90-NDdk:-Mkh_Z025ThY_Bx2jK6t:bp7vbga) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d40c00d8cf7926b0ce5e2bada60920eb370c7d7c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L90)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

That's a great question. I'd say yes, let's say the manifest must contain a glob for files in the same directory (in other words, no slashes). WDYT about this? If OK, I'll add a comment here specifying that.
</blockquote></details>

sounds good.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jonmolle and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52#-Mkh8oYh731Xm90-NDdk:-Mki2DnE9zCzAyyr9WIw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/d40c00d8cf7926b0ce5e2bada60920eb370c7d7c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L90)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sounds good.
</blockquote></details>

Done.

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/52)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle and @stevenwarejones)

**Pull request merged**
