### PR TITLE
Update ProtocolConfig and its usage in the Public API.

### PR DESCRIPTION
**Pull request by wangyaopw**
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Fuserstory%2F606023914123%2Ftasks&view=2c2927c0-626b-4740-8620-af2a93b7d623

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/43)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @oliver-amzn)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Comment by wangyaopw** [comment]
The PR is updated significantly, please review again.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Review by wangyaopw — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)

**Pull request merged**
