### PR TITLE
Add `capabilities` field to `DataProvider` resource type.

### PR DESCRIPTION
**Pull request by SanjayVas**
This includes a corresponding `ReplaceDataProviderCapabilities` method in the `DataProviders` service.

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NqTzTMEEiw8044dNLJP:bwczms1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
> ```proto
>   message Capabilities {
>     // Whether the Honest Majority Share Shuffle (HMSS) protocol is supported.
>     bool honest_majority_share_shuffle_supported = 1;
> ```

@kungfucraig 

The alternative here would be something like

```proto
enum CapabilityStatus {
  UNSUPPORTED = 0;
  SUPPORTED = 1;
  // Possibly more values added later.
}

CapabilityStatus honest_majority_share_shuffle = 1;
```

The semantics for adding an enum value here w.r.t. backwards compatibility here are more complicated however than that of adding a new `bool` field. For one, the enum value would need to apply to *all* capability fields.

Note that in the `bool` case, "supported" is part of the field rather than the status.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NqU1Y7t1bTmpMHuCaPA:bnltzko) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@kungfucraig 

The alternative here would be something like

```proto
enum CapabilityStatus {
  UNSUPPORTED = 0;
  SUPPORTED = 1;
  // Possibly more values added later.
}

CapabilityStatus honest_majority_share_shuffle = 1;
```

The semantics for adding an enum value here w.r.t. backwards compatibility here are more complicated however than that of adding a new `bool` field. For one, the enum value would need to apply to *all* capability fields.

Note that in the `bool` case, "supported" is part of the field rather than the status.
</blockquote></details>

Seems like we could support boolean capabilities and CapabilityStatus capabilities in the future if we wanted to.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-Nq_ST-s4az4UJsletm9:b-jkvmsw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Seems like we could support boolean capabilities and CapabilityStatus capabilities in the future if we wanted to.
</blockquote></details>

I think we need a supported from datetime.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-Nq_cvdK241WLbVVB5TL:b-5t9yy9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think we need a supported from datetime.
</blockquote></details>

and possibly a supported until field for protocols an EDP will _stop_ supporting at a certain date.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NqUWi1f8nxg-ibo1WTc:bkh1wvd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
> I think we need a supported from datetime.

What is the use case? AFAICT the system only ever needs to know what is supported at Measurement creation time.

> and possibly a supported until field for protocols an EDP will _stop_ supporting at a certain date.

Also not needed for the same reason.

The basic idea is that each Kingdom will have a configuration of required protocols. These are enforced at Measurement creation time (enforcing them at EDP update time doesn't really make sense, and also may just get EDPs to lie about what they support). Note that this enforcement of requirements is done independently of what protocol the Measurement uses.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-Nqj6Tny3UH7s8DImSgz:bua6ksc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I think we need a supported from datetime.

What is the use case? AFAICT the system only ever needs to know what is supported at Measurement creation time.

> and possibly a supported until field for protocols an EDP will _stop_ supporting at a certain date.

Also not needed for the same reason.

The basic idea is that each Kingdom will have a configuration of required protocols. These are enforced at Measurement creation time (enforcing them at EDP update time doesn't really make sense, and also may just get EDPs to lie about what they support). Note that this enforcement of requirements is done independently of what protocol the Measurement uses.
</blockquote></details>

Added a comment about Measurement creation time.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NqjriRTEc7mggFhrCmp:bpd6556) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Added a comment about Measurement creation time.
</blockquote></details>

So, the kingdom operator will decide what EDPs have what capabilities and set these booleans accordingly?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NqnDjNYEPonbUdUM0Fm:b-igw7t4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

So, the kingdom operator will decide what EDPs have what capabilities and set these booleans accordingly?
</blockquote></details>

No, EDPs still have to indicate their capabilities. It's that the Kingdom operator will have a configuration of required capabilities that all EDPs **must** have, or else any Measurement involving that EDP will fail.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-Nqnq6bx5mzdYxUv9Nz7:b-aqfbqh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No, EDPs still have to indicate their capabilities. It's that the Kingdom operator will have a configuration of required capabilities that all EDPs **must** have, or else any Measurement involving that EDP will fail.
</blockquote></details>

A Capability structure with a boolean (or enum) inside would be nice. I can see where we don't seem to need the dates right now, but having a richer structure will give us some flexability, pretty much for free, should we ever need dates or anything else.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-Nrk7u9kCFH-pLGPKKdc:b32t10u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

A Capability structure with a boolean (or enum) inside would be nice. I can see where we don't seem to need the dates right now, but having a richer structure will give us some flexability, pretty much for free, should we ever need dates or anything else.
</blockquote></details>

+1 to Craig.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-Nrl6tXi2UwomV0NXyO_:b-7lseky) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1 to Craig.
</blockquote></details>

I feel like the above would be significantly over-engineering something that's meant to be akin to command-line flags. The common flow is expected to be

1. Introduce capability (flag)
2. All EDPs eventually support capability
3. Capability is marked as required (equivalent to flipping the flag to true for all)
4. Capability field is deprecated and deleted (value is assumed)

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NrlWrWH50QH-RfWFm5m:br5axjr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I feel like the above would be significantly over-engineering something that's meant to be akin to command-line flags. The common flow is expected to be

1. Introduce capability (flag)
2. All EDPs eventually support capability
3. Capability is marked as required (equivalent to flipping the flag to true for all)
4. Capability field is deprecated and deleted (value is assumed)
</blockquote></details>

What if we want an MC allow list for the capability?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NrlkSaM19LHtsVanIUG:b5h5ksq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What if we want an MC allow list for the capability?
</blockquote></details>

That's not at all considered by the capability design. Do you want to introduce that requirement and redesign?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NrllhUjChuvBQCaU_7N:b-yotlzb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's not at all considered by the capability design. Do you want to introduce that requirement and redesign?
</blockquote></details>

To clarify what I mean, there's currently no relation between this and any kind of MC allow list as that hasn't been considered. My inclination would be to keep the two features separate: EDPs list their capabilities and Kingdom keeps a list of allowed features per MC. EDP capabilities and allowed features need not map 1:1.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NrpfGnf7LKjMiPl-hEl:b-qse1td) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify what I mean, there's currently no relation between this and any kind of MC allow list as that hasn't been considered. My inclination would be to keep the two features separate: EDPs list their capabilities and Kingdom keeps a list of allowed features per MC. EDP capabilities and allowed features need not map 1:1.
</blockquote></details>

Okay, let's go with this. I think if we've gotten it wrong it's not hard to change.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-NrqcIyZ8HTYeJgf9b5g:b-bs9jh3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Okay, let's go with this. I think if we've gotten it wrong it's not hard to change.
</blockquote></details>

i'm a little confused why a capability start/end date are not needed. If EDP A starts supporting a new capability starting on some future date or will stop supporting it on some future date, the Kingdom can use this data to select those capabilities when measurements arrive.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto` line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199#-NqTzTMEEiw8044dNLJO:-Nrr0Doz8dHYoEZVrSbw:b2ljwx3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/8a1e491350d89333343dcca9f534cc68fbaf9736/src/main/proto/wfa/measurement/api/v2alpha/data_provider.proto#L78)):*
> If EDP A starts supporting a new capability starting on some future date or will stop supporting it on some future date

That's not a supported/expected use case. Again, this is intended just to help control feature rollouts. There are exactly two supported paths:

1. The feature flag gets "flipped", meaning the capability is always required to be supported
2. The feature gets deprecated, meaning the capability is no longer relevant.

All capabilities are meant to be short-lived.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @kungfucraig)

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/199)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request closed without merging**
