### PR TITLE
Add /ModelProviders.Get method

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47#-MjjiOtr3DiTM4C9YFNG:-MjjiOtsAiPH0LCnbfj6:buotpuy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/aafb13885a1296c1b20a394f600aae8fea7a62df/src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto#L27)):*
> ```protobuf
> 
> // Service for interacting with `ModelProvider` resources.
> service ModelProviders {
> ```

Why do we need this?

I thought an internal admin tool was going to be creating EDPs and MPs by calling internal APIs. FYI @sanjayvas

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47#-MjjiOtr3DiTM4C9YFNG:-Mjjiiry6yyyLLFOFPYt:b2nnxtu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/aafb13885a1296c1b20a394f600aae8fea7a62df/src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why do we need this?

I thought an internal admin tool was going to be creating EDPs and MPs by calling internal APIs. FYI @sanjayvas 
</blockquote></details>

Yeah, my assumption was that we weren't going to be allowing self-service registration. This means that EDPs and MPs are either added by internal API call or config file (depending on whether we want them to be dynamically updated).

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47#-MjjiOtr3DiTM4C9YFNG:-Mjjm4KQ44YAiaKvmgM1:bwl8a24) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/aafb13885a1296c1b20a394f600aae8fea7a62df/src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yeah, my assumption was that we weren't going to be allowing self-service registration. This means that EDPs and MPs are either added by internal API call or config file (depending on whether we want them to be dynamically updated).
</blockquote></details>

But we have data_providers_service in the public API, and it is already implemented and used in the correctness test.

Whoever in the kingdom registers EDPs and MPs can either call the internal API or the public API I guess. We just need to hide these two services in the public API (maybe not possible?)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47#-MjjiOtr3DiTM4C9YFNG:-MjjpXzQ0hK-ldJGINEQ:bsnbcg7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/aafb13885a1296c1b20a394f600aae8fea7a62df/src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto#L27)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

But we have data_providers_service in the public API, and it is already implemented and used in the correctness test.

Whoever in the kingdom registers EDPs and MPs can either call the internal API or the public API I guess. We just need to hide these two services in the public API (maybe not possible?)
</blockquote></details>

I'd prefer we drop them unless we have a hard need for them

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @kgaynor, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47#-MjjiOtr3DiTM4C9YFNG:-MjjpJFL9ojUHupN61H1:b-61axu7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/aafb13885a1296c1b20a394f600aae8fea7a62df/src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'd prefer we drop them unless we have a hard need for them
</blockquote></details>

So, for Panel Match Integration tests, we will be using/testing public API to create a RecurringExchange. To be able to create RecurringExchange we need to create EDP and MP also using public API. Correct me if I am wrong.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @kgaynor, @stevenwarejones, and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47#-MjjiOtr3DiTM4C9YFNG:-Mjjq-M-8ce0fvL4lccF:b-z9mc2s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/aafb13885a1296c1b20a394f600aae8fea7a62df/src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto#L27)):*
> But we have data_providers_service in the public API, and it is already implemented and used in the correctness test.

The intent is to drop `CreateDataProvider` from the public API. You need to interact with the CMMS operator to set up mTLS anyway. The rest of the public `DataProviders` service is fine.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47#-MjjiOtr3DiTM4C9YFNG:-Mjjs8H3BrKBmwODvoRk:b-iuigoo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/aafb13885a1296c1b20a394f600aae8fea7a62df/src/main/proto/wfa/measurement/api/v2alpha/model_providers_service.proto#L27)):*
> So, for Panel Match Integration tests, we will be using/testing public API to create a RecurringExchange. To be able to create RecurringExchange we need to create EDP and MP also using public API. Correct me if I am wrong.

We should use internal APIs to create EDP, MP, RecurringExchange.

Use public APIs for everything else.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

**Review by wangyaopw — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, @SanjayVas, @stevenwarejones, and @yunyeng)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @kgaynor, and @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @kgaynor, and @SanjayVas)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @kgaynor, and @SanjayVas)

**Pull request merged**
