### PR TITLE
change rlwe parameters from serialized bytes to Any

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87)

### CODE REVIEW

**Review by robinsons — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87#-MvL6Jtd5gI3i5U72c3O:-MvL6Jte-Xnwbz6-cRUV:b-mcd8jk) (no related file):*
What's the use case for something other than serialized `private_membership.batch.Parameters`?

---

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @robinsons and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87#-MvL6Jtd5gI3i5U72c3O:-MvLAhLr9Su1uEJIsO2V:bkylpw6) (no related file):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

What's the use case for something other than serialized `private_membership.batch.Parameters`?
</blockquote></details>

This is part of https://rally1.rallydev.com/#/604612930531d/search?detail=%2Ftask%2Fbb7e9df2-f4f5-4b92-b5ef-066098d438a5&keywords=Any that Eli and I made.

The use case is to not tie the proto to any particular impl.

---

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @robinsons and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87#-MvL6Jtd5gI3i5U72c3O:-MvLAsDO685B25nxz96y:b-4y0v50) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This is part of https://rally1.rallydev.com/#/604612930531d/search?detail=%2Ftask%2Fbb7e9df2-f4f5-4b92-b5ef-066098d438a5&keywords=Any that Eli and I made.

The use case is to not tie the proto to any particular impl.
</blockquote></details>

eg - not tie the workflow step to a particular impl.

---

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @robinsons and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87#-MvL6Jtd5gI3i5U72c3O:-MvLBUEgEiTnoJsutwVE:bpvtjka) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

eg - not tie the workflow step to a particular impl.
</blockquote></details>

this is also because these parameters make it into the actual workflow.

---

**Review by robinsons — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/87#-MvL6Jtd5gI3i5U72c3O:-MvL_1gaBOP3VvZLdua-:bcr5s31) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this is also because these parameters make it into the actual workflow.
</blockquote></details>

Got it, thanks.

---

**Pull request merged**
