### PR TITLE
Add NextExchangeDate field to RecurringExchange

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49)* status: all files reviewed, 2 unresolved discussions (waiting on @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49#-MkJkA5T95zN0XZMIBTJ:-MkJkA5U5Rhhgmu5DNv9:b-bli1pk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/48df7c1fe65a5ae148b8ca485ffe34dfaf474a19/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L56)):*
> ```protobuf
>   State state = 6;
> 
>   // When to start new Exchanges.
> ```

"The date of the next Exchange" might be more accurate?
___
*[src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49#-MkJjwuE2jQWPYFw4tGR:-MkJjwuE2jQWPYFw4tGS:bg7qulz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/48df7c1fe65a5ae148b8ca485ffe34dfaf474a19/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L57)):*
> ```protobuf
> 
>   // When to start new Exchanges.
>   google.type.Date next_exchange_date = 7;
> ```

In addition, can you add `first_exchange_date` to the `ExchangeWorkflow` message?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49#-MkJkA5T95zN0XZMIBTJ:-MkK4IAa99vwCF5a3awz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/48df7c1fe65a5ae148b8ca485ffe34dfaf474a19/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L56)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

"The date of the next Exchange" might be more accurate?
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49#-MkJjwuE2jQWPYFw4tGR:-MkK4IQ_0KitSUGWyZFV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/48df7c1fe65a5ae148b8ca485ffe34dfaf474a19/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In addition, can you add `first_exchange_date` to the `ExchangeWorkflow` message?
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @kgaynor, and @yunyeng)

___
*[src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49#-MkJjwuE2jQWPYFw4tGR:-MkODE508NmVGL7a5jT6:b-3c56oq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/48df7c1fe65a5ae148b8ca485ffe34dfaf474a19/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L57)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I wanted:

* In `RecurringExchange`: `next_exchange_date`
* In `ExchangeWorkflow`: `first_exchange_date`

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @kgaynor, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49#-MkJjwuE2jQWPYFw4tGR:-Mkc2OFF8VdLZQ0lp_Fa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/48df7c1fe65a5ae148b8ca485ffe34dfaf474a19/src/main/proto/wfa/measurement/api/v2alpha/recurring_exchange.proto#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What I wanted:

* In `RecurringExchange`: `next_exchange_date`
* In `ExchangeWorkflow`: `first_exchange_date`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @kgaynor)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @kgaynor)

**Pull request merged**
