### PR TITLE
Add vid sampling for impression and  Duration measurements

### PR DESCRIPTION
**Pull request by uakyol**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/104)

### CODE REVIEW

**Review by tristanvuong2021 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/104)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @matthewclegg, @stevenwarejones, and @uakyol)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/104#-N2rgqs10Mb2kubZunxD:-N2rgqs10Mb2kubZunxE:b-yl2fl3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/baee4cda1012ba10aadea61681a150a2f91be9d8/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L46)):*
> ```protobuf
> 
>   // Range of VIDs that will be included in this measurement
>   VidSamplingInterval vid_sampling_interval = 4;
> ```

Field number here and in the measurement type oneof should be changed. Right now, it is 4, 3, 4, 5. Should be 3, 4, 5, 6.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/104)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/104#-N2rgqs10Mb2kubZunxD:-N2rsRco7oCs9g3kiY8v:bmz6evz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/baee4cda1012ba10aadea61681a150a2f91be9d8/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L46)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Field number here and in the measurement type oneof should be changed. Right now, it is 4, 3, 4, 5. Should be 3, 4, 5, 6.
</blockquote></details>

or just change this to 6

**Review by uakyol — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/104)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto` line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/104#-N2rgqs10Mb2kubZunxD:-N2wR_Xl1EVEU2bEUkXi:bcseode) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/baee4cda1012ba10aadea61681a150a2f91be9d8/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

or just change this to 6
</blockquote></details>

:facepalm: thank you!

**Review by tristanvuong2021 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
