### PR TITLE
add explicit shared input and output labels to exchange workflow

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31)

### CODE REVIEW

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[docs/panelmatch/example-exchange-workflow.textproto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-Mb7uxtQ2Yx2tLxzTCvL:-Mb7uxtQ2Yx2tLxzTCvM:b-rlg63p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ed0d5939c5893f7dc493850e2e24971bd31ad23d/docs/panelmatch/example-exchange-workflow.textproto#L17)):*
> ```
>   party: MODEL_PROVIDER
> 
>   input {}
> ```

Input is always empty in these example steps. Let's discuss.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-Mb7upFZ9Vc_Wjx-jO7D:-Mb7upFZ9Vc_Wjx-jO7E:b-yycj6d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ed0d5939c5893f7dc493850e2e24971bd31ad23d/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L72)):*
> ```protobuf
> 
>     // Applies deterministic, commutative encryption to the input data.
>     message EncryptAndShareStep {
> ```

Should I separate this out into EncryptAndShare and ReEncryptAndShare?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[docs/panelmatch/example-exchange-workflow.textproto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-Mb7uxtQ2Yx2tLxzTCvL:-Mb8KGLF975RTQ2kS5YN:b6nc2fo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ed0d5939c5893f7dc493850e2e24971bd31ad23d/docs/panelmatch/example-exchange-workflow.textproto#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Input is always empty in these example steps. Let's discuss.
</blockquote></details>

This is very deliberately by design. We'll chat about this.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-Mb8KUti7rJm-yKPA2hL:-Mb8KUti7rJm-yKPA2hM:bhtq8df) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ed0d5939c5893f7dc493850e2e24971bd31ad23d/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L51)):*
> ```protobuf
>     // Inputs to the protocol are provided via InputStep step types -- this
>     // ensures that all inputs to all steps appear as some output label.
>     map<string, string> input_labels = 3;
> ```

Would it make sense to name them `private_input_labels` and `shared_input_labels`?

Alternatively, what about not separating them here, but adding a repeated field in the `ExchangeWorkflow` message called `repeated string shared_labels` that just lists all the labels that are shared.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-Mb7upFZ9Vc_Wjx-jO7D:-Mb8KQDZC2WNaGZEeYtJ:b9y1bfs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ed0d5939c5893f7dc493850e2e24971bd31ad23d/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L72)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Should I separate this out into EncryptAndShare and ReEncryptAndShare?
</blockquote></details>

Yes please

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-Mb8KUti7rJm-yKPA2hL:-MbCcUwwDuGM5Lt7txpx:b-i1deya) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ed0d5939c5893f7dc493850e2e24971bd31ad23d/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Would it make sense to name them `private_input_labels` and `shared_input_labels`?

Alternatively, what about not separating them here, but adding a repeated field in the `ExchangeWorkflow` message called `repeated string shared_labels` that just lists all the labels that are shared.
</blockquote></details>

i like private. I was wondering if I should rename them but wasn't sure.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31)* status: all files reviewed, 7 unresolved discussions (waiting on @stevenwarejones)

___
*[docs/panelmatch/example-exchange-workflow.textproto, line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-MbCfN63A1tNqRDieUg1:-MbCfN63A1tNqRDieUg2:bosg8ss) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/25424eaa090decfa7806c901a6dd5778ff72fc5c/docs/panelmatch/example-exchange-workflow.textproto#L19)):*
> ```
>   input {}
> 
>   shared_input_labels {}
> ```

You should omit empty repeated fields from the textproto. What you're doing here is actually creating a `shared_input_labels` entry with no key and no value.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-Mb8KUti7rJm-yKPA2hL:-MbCeTxmClKe0P_nHtDj:b-6sk4dy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/ed0d5939c5893f7dc493850e2e24971bd31ad23d/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i like private. I was wondering if I should rename them but wasn't sure.
</blockquote></details>

Please update `exchange_step.proto` -- it has some references to `step.input_labels`.
Also `exchange_step_attempts_service.proto` -- it references `step.output_labels`.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-MbCeiYz8WwqRCFGmYFL:-MbCeiYz8WwqRCFGmYFM:b-x79ydf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/25424eaa090decfa7806c901a6dd5778ff72fc5c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L71)):*
> ```protobuf
>     message TableQueryStep {}
> 
>     // Applies deterministic, commutative encryption to the input data.
> ```

Can you clarify that this is plaintext input data?
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-MbCenhaElgm21lliago:-MbCenhaElgm21lliagp:b-mwt28k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/25424eaa090decfa7806c901a6dd5778ff72fc5c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L74)):*
> ```protobuf
>     message EncryptAndShareStep {}
> 
>     // Applies a second layer of deterministic, commutative encryption to the input data.
> ```

Technically, it's just an "additional" layer -- it could add a 3rd or 4th layer in some other protocol. Might also be worthwhile clarifying that the input MUST be ciphertexts.
___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-MbCf8aO91bPqZTxFyCq:-MbCf8aO91bPqZTxFyCr:b-j3olyg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/25424eaa090decfa7806c901a6dd5778ff72fc5c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L90)):*
> ```protobuf
>       IntersectAndValidateStep intersect_and_validate = 5;
>       TableQueryStep table_query = 6;
>       EncryptAndShareStep encrypt_and_share = 7;
> ```

While we're changing these, would it make more sense to name them just "Encrypt" and "ReEncrypt" (dropping the "AndShare")? There might be protocols were we don't actually want to share and the sharing is not fundamentally built in.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto, line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-MbCf8aO91bPqZTxFyCq:-MbCspWa0pYpSQwa5X9H:b-7stw28) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/25424eaa090decfa7806c901a6dd5778ff72fc5c/src/main/proto/wfa/measurement/api/v2alpha/exchange_workflow.proto#L90)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

While we're changing these, would it make more sense to name them just "Encrypt" and "ReEncrypt" (dropping the "AndShare")? There might be protocols were we don't actually want to share and the sharing is not fundamentally built in.
</blockquote></details>

i agree. The sharing is actually now done in the shared_outputs. Any step could be `andShare` now

**Review by efoxepstein — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[docs/panelmatch/example-exchange-workflow.textproto, line 98 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31#-MbHi2yoALPveJP-Q4kK:-MbHi2ypA79h3sBN15KL:bcerc9f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/28f11048c5bf4f98cd0c1e618c55b0d3608dd803/docs/panelmatch/example-exchange-workflow.textproto#L98)):*
> ```
>   party: DATA_PROVIDER
> 
>   # Ensure there are are betweem 1000 and 10,000 panelists and 99% of them
> ```

Nit: "between" (see last character)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/31)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Pull request merged**
