### PR TITLE
Add direct measurement result to measurement.

### PR DESCRIPTION
**Pull request by tristanvuong2021**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 143 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98#-Mzq7spK-AiEuaEAVmmk:-Mzq7spK-AiEuaEAVmml:b3hogve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f48ab6a22c7c2e36ad1e7a2b3951a69f78a80e69/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L143)):*
> ```protobuf
>   }
> 
>   // This can be one of multiple things.
> ```

Let's not change the structure of the encrypted result itself. That is to say that the encrypted result should always be an encrypted `SignedData` containing a serialized `Result`. We should have e.g. an `ImpressionCountResult` (or whatever we called the measurement type) inside `Result`. 

What we need to change is that instead of the encrypted result being a single value signed by the aggregator certificate, we need a repeated structure that has tuples of certificate resource name and encrypted result. The party that gave the result is the parent of the Certificate resource. Concretely, this means dropping the `aggregator_certificate` field.



_Code quote:_
```protobuf
// This can be one of multiple things.
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 143 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98#-Mzq7spK-AiEuaEAVmmk:-MzqTLyFAri46TACiphU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f48ab6a22c7c2e36ad1e7a2b3951a69f78a80e69/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L143)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's not change the structure of the encrypted result itself. That is to say that the encrypted result should always be an encrypted `SignedData` containing a serialized `Result`. We should have e.g. an `ImpressionCountResult` (or whatever we called the measurement type) inside `Result`. 

What we need to change is that instead of the encrypted result being a single value signed by the aggregator certificate, we need a repeated structure that has tuples of certificate resource name and encrypted result. The party that gave the result is the parent of the Certificate resource. Concretely, this means dropping the `aggregator_certificate` field.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 143 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98#-Mzq7spK-AiEuaEAVmmk:-Mzr3HRC7fQG5QATCtc9:bagw5y1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f48ab6a22c7c2e36ad1e7a2b3951a69f78a80e69/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L143)):*
> We should have e.g. an `ImpressionCountResult` (or whatever we called the measurement type) inside `Result`.

Sorry, this should have said that we should have an `impression` field inside of `Result`.

We should still have a `Result` message that contains the fields for the different result information. This way you don't need to know the specific message type in order to deserialize the result. Your wrapper message for the (encrypted_result, certificate) tuple can be named something else.
___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 145 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98#-Mzr4Orj6BNbUUe4a4G9:-Mzr4Orj6BNbUUe4a4GA:bw9zs25) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/2da8793221b597867cd1b79c8a8c805b196df1d3/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L145)):*
> ```protobuf
>     // The encryption uses the `measurement_public_key` from `measurement_spec`
>     // as the recipient public key.
>     bytes encryptedResult = 1;
> ```

`encrypted_result`



_Code quote:_
```protobuf
encryptedResult
```

**Review by tristanvuong2021 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 143 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98#-Mzq7spK-AiEuaEAVmmk:-MzrJxE--qWR_Rzv_gDS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/f48ab6a22c7c2e36ad1e7a2b3951a69f78a80e69/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L143)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> We should have e.g. an `ImpressionCountResult` (or whatever we called the measurement type) inside `Result`.

Sorry, this should have said that we should have an `impression` field inside of `Result`.

We should still have a `Result` message that contains the fields for the different result information. This way you don't need to know the specific message type in order to deserialize the result. Your wrapper message for the (encrypted_result, certificate) tuple can be named something else.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 145 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98#-Mzr4Orj6BNbUUe4a4G9:-MzrJxbQ8dTJG-62x3A2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/2da8793221b597867cd1b79c8a8c805b196df1d3/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L145)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`encrypted_result`
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 127 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98#-N-8ztjwEYmF37SldJoE:-N-8ztjwEYmF37SldJoF:b-ay3jxy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/28cafe94d08a6a946c7d71851cf038c5a3ea1554/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L127)):*
> ```protobuf
>     Impression impression = 3;
> 
>     message Duration {
> ```

what about using com.google.protobuf.Duration?

**Comment by tristanvuong2021** [comment]
*[src/main/proto/wfa/measurement/api/v2alpha/measurement.proto, line 127 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98#-N-8ztjwEYmF37SldJoE:-N-96bp6-FkBc04zJb1V:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/28cafe94d08a6a946c7d71851cf038c5a3ea1554/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L127)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what about using com.google.protobuf.Duration?
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/98)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

**Pull request merged**
