### PR TITLE
Add encrypt storage step

### PR DESCRIPTION
**Pull request by stevenwarejones**
Used for encrypting hashes that are shared

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69#-Mnbccnl6QDeGJaGsJR6:-Mnbccnl6QDeGJaGsJR7:bxeps54) (no related file):*
Can you attach the PNG emitted by graphviz for this? https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/tools/ExchangeWorkflowToGraphvizMain.kt will generate it, then something like `dot -Tpng something.dot > graph.png` should render it, I think

---

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69#-Mnbccnl6QDeGJaGsJR6:-Moj8szeBT-mwJtQRYN_:blwaac9) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you attach the PNG emitted by graphviz for this? https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/tools/ExchangeWorkflowToGraphvizMain.kt will generate it, then something like `dot -Tpng something.dot > graph.png` should render it, I think
</blockquote></details>

What's up with the black blobs?

---

**Comment by stevenwarejones** [comment]
graph3

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[docs/panelmatch/example-exchange-workflow.textproto, line 196 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69#-MooaA91-zQzZ4x4h26u:-MooaA91-zQzZ4x4h26v:b-il7rnr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/678a8f5029dafdf7c45c74f5ca4d4c693c59ba09/docs/panelmatch/example-exchange-workflow.textproto#L196)):*
> ```
>   copy_from_previous_exchange_step {}
> 
>   input_labels { key: "input" value: "edp-single-blinded-join-keys-audit-trail" }
> ```

Can you keep this line? See https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L196

(Or if you remove this, please also update `CopyFromPreviousExchangeTask` and `ExchangeTaskMapperForJoinKeyExchange`)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69#-Mnbccnl6QDeGJaGsJR6:-MrOe76gDl5I4YlQUenq:bd4kb81) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What's up with the black blobs?
</blockquote></details>


Done. 

---
___
*[docs/panelmatch/example-exchange-workflow.textproto, line 196 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69#-MooaA91-zQzZ4x4h26u:-MrOWzCNBP0Hb55LvdAU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/678a8f5029dafdf7c45c74f5ca4d4c693c59ba09/docs/panelmatch/example-exchange-workflow.textproto#L196)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you keep this line? See https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L196

(Or if you remove this, please also update `CopyFromPreviousExchangeTask` and `ExchangeTaskMapperForJoinKeyExchange`)
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 15 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[docs/panelmatch/example-exchange-workflow.textproto, line 0 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69#-Ms_cLMBCZzRP6MvAu_b:-Ms_cLMD7ypCg-66Z5DN:b2tlw01) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/2ce90c59f7be6946177982335769984e7896b274/docs/panelmatch/example-exchange-workflow.textproto#L0)):*
Why is this file deleted?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[docs/panelmatch/example-exchange-workflow.textproto, line  at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69#-Ms_cLMBCZzRP6MvAu_b:-Ms_ttMf4wnteHYj-HcX:b-q8ubqr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/2ce90c59f7be6946177982335769984e7896b274/docs/panelmatch/example-exchange-workflow.textproto#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is this file deleted?
</blockquote></details>

I think its been effectively replaced by the full workflow tests in panel exchange client. This one is hard to maintain. It lacks tests and bugs are easily introduced.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/69)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
