### PR TITLE
Add a name field to Event Template Descriptor

### PR DESCRIPTION
**Pull request by duliomatos1**
This field will be used to reference the template e.g. when using it in a cel expression for filtering

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @duliomatos1, @stevenwarejones, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-My8uFQv15o2gAHXLXgb:-My8uFQv15o2gAHXLXgc:b-lisstf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e3d89a0a9c86831300103b360253926074abfb04/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L34)):*
> ```protobuf
> // Metadata about an Event Template.
> message EventTemplateDescriptor {
>   // Name used to reference this Event Template. Required.
> ```

This should also be documented as Immutable. Should also list the restrictions/requirements.

I assume this is for the field name in the unified event message, so e.g. it should follow the [naming conventions](https://developers.google.com/protocol-buffers/docs/style#message_and_field_names) for a protobuf field. I assume this also needs to be unique within some notion of a namespace, so we should also document that requirement.

**Review by uakyol — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @duliomatos1, and @stevenwarejones)

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @stevenwarejones, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-My8uFQv15o2gAHXLXgb:-MyCXruZ5Aq2udvz9iwd:bm6y7pk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e3d89a0a9c86831300103b360253926074abfb04/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should also be documented as Immutable. Should also list the restrictions/requirements.

I assume this is for the field name in the unified event message, so e.g. it should follow the [naming conventions](https://developers.google.com/protocol-buffers/docs/style#message_and_field_names) for a protobuf field. I assume this also needs to be unique within some notion of a namespace, so we should also document that requirement.
</blockquote></details>

makes a lot of sense. Was thinking about the unified event message exactly as something like:

```
message Event {
  optional EventTemplateDescriptor template_name1 = 1;
  optional EventTemplateDescriptor template_name2 = 2;
  ...
}
```
As the way to have the event as a collection of at most one of each event template.
Do you think this is a good way forward, @uakyol @sanjayvas?
It's more exact than using a `List<EventTemplateDescriptor>`. It requires that we validate that every new template is added here though.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-MyDja4O9WMMBx0hdz1q:-MyDja4O9WMMBx0hdz1r:bem9a55) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/807a2680459af495b3699c8e0565b1c8c6507cde/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L34)):*
> ```protobuf
> // Metadata about an Event Template.
> message EventTemplateDescriptor {
>   // Name used to reference this Event Template. Required.
> ```

Still need to add `Immutable.` here to indicate that this doesn't change once created.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-MyDjPxF84gJJGjU4Y9K:-MyDjPxG6oilgk2_X5gI:bhjrum7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/807a2680459af495b3699c8e0565b1c8c6507cde/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L36)):*
> ```protobuf
>   // Name used to reference this Event Template. Required.
>   // Must follow the naming convention for protocol buffers fields.
>   // Must be unique between all event template message types.
> ```

nit: I'm assuming it's not "all" but rather "all within a given template registry"



_Code quote:_
```protobuf
 all event template message types
```
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-MyDjZ5V4S9lKKr9E7_D:-MyDjZ5V4S9lKKr9E7_E:b-7rn9yp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/807a2680459af495b3699c8e0565b1c8c6507cde/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L36)):*
> ```protobuf
>   // Name used to reference this Event Template. Required.
>   // Must follow the naming convention for protocol buffers fields.
>   // Must be unique between all event template message types.
> ```

nit: put the URL here for reference



_Code quote:_
```protobuf
naming convention for protocol buffers fields.
```

**Comment by uakyol** [comment]
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-My8uFQv15o2gAHXLXgb:-MyEAUPh8IZA46PATiJJ:b-mudwek) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e3d89a0a9c86831300103b360253926074abfb04/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L34)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

makes a lot of sense. Was thinking about the unified event message exactly as something like:

```
message Event {
  optional EventTemplateDescriptor template_name1 = 1;
  optional EventTemplateDescriptor template_name2 = 2;
  ...
}
```
As the way to have the event as a collection of at most one of each event template.
Do you think this is a good way forward, @uakyol @sanjayvas?
It's more exact than using a `List<EventTemplateDescriptor>`. It requires that we validate that every new template is added here though.
</blockquote></details>

@robinsons can you please help here.

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-MyDja4O9WMMBx0hdz1q:-MyEAyZ21mWDrgXVxC-i:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/807a2680459af495b3699c8e0565b1c8c6507cde/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Still need to add `Immutable.` here to indicate that this doesn't change once created.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-MyDjPxF84gJJGjU4Y9K:-MyEB0zLC889Nbditybi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/807a2680459af495b3699c8e0565b1c8c6507cde/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I'm assuming it's not "all" but rather "all within a given template registry"
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-MyDjZ5V4S9lKKr9E7_D:-MyEB23z6NGbwTYE-xWU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/807a2680459af495b3699c8e0565b1c8c6507cde/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: put the URL here for reference
</blockquote></details>

Done.

**Review by duliomatos1 — COMMENTED** [review]
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-My8uFQv15o2gAHXLXgb:-MyEEiNPDdNooSvhyi7R:bk4ypvc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e3d89a0a9c86831300103b360253926074abfb04/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L34)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

@robinsons can you please help here.
</blockquote></details>

It looks like the comment was updated per Sanjay's suggestion. We could have a follow-up discussion or doc about how we intend to enforce the uniqueness requirement, but I don't think that needs to block this PR. It could be something as simple as prefixing each `name` with the name of the party that manages that template, e.g. `google_{some_template_name}`.

**Comment by uakyol** [comment]
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92#-My8uFQv15o2gAHXLXgb:-MyEQWhb9hmVxUlt5A52:b-1zz2t0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/e3d89a0a9c86831300103b360253926074abfb04/src/main/proto/wfa/measurement/api/v2alpha/event_annotations.proto#L34)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

It looks like the comment was updated per Sanjay's suggestion. We could have a follow-up discussion or doc about how we intend to enforce the uniqueness requirement, but I don't think that needs to block this PR. It could be something as simple as prefixing each `name` with the name of the party that manages that template, e.g. `google_{some_template_name}`.
</blockquote></details>

I would prefer having optional fields. To use in the CEL expression, we will need to prefix each name with the "template_name1" , "template_name2" in Dulio's example. The problem is that if an EDP wants to use a template they will need to add it to the Event message. Also, we might want to keep this event message up to date as we add new templates. Maybe this is ok if we document this requirement.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement-api/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @stevenwarejones)

**Comment by uakyol** [comment]
It seems like this PR is closed somehow : https://github.com/world-federation-of-advertisers/cross-media-measurement/pulls/duliomatos1 do you know what happened Dulio?

**Comment by uakyol** [comment]
Sorry, was looking at wrong repo

**Pull request merged**
